// Code generated by codeinfra-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package primitive

import (
	"context"
	"reflect"

	"errors"
	"example.com/codeinfra-primitive/sdk/go/v7/primitive/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

type Resource struct {
	codeinfra.CustomResourceState

	Boolean     codeinfra.BoolOutput         `codeinfra:"boolean"`
	BooleanMap  codeinfra.BoolMapOutput      `codeinfra:"booleanMap"`
	Float       codeinfra.Float64Output      `codeinfra:"float"`
	Integer     codeinfra.IntOutput          `codeinfra:"integer"`
	NumberArray codeinfra.Float64ArrayOutput `codeinfra:"numberArray"`
	String      codeinfra.StringOutput       `codeinfra:"string"`
}

// NewResource registers a new resource with the given unique name, arguments, and options.
func NewResource(ctx *codeinfra.Context,
	name string, args *ResourceArgs, opts ...codeinfra.ResourceOption) (*Resource, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Boolean == nil {
		return nil, errors.New("invalid value for required argument 'Boolean'")
	}
	if args.BooleanMap == nil {
		return nil, errors.New("invalid value for required argument 'BooleanMap'")
	}
	if args.Float == nil {
		return nil, errors.New("invalid value for required argument 'Float'")
	}
	if args.Integer == nil {
		return nil, errors.New("invalid value for required argument 'Integer'")
	}
	if args.NumberArray == nil {
		return nil, errors.New("invalid value for required argument 'NumberArray'")
	}
	if args.String == nil {
		return nil, errors.New("invalid value for required argument 'String'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Resource
	err := ctx.RegisterResource("primitive:index:Resource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResource gets an existing Resource resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResource(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *ResourceState, opts ...codeinfra.ResourceOption) (*Resource, error) {
	var resource Resource
	err := ctx.ReadResource("primitive:index:Resource", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Resource resources.
type resourceState struct {
}

type ResourceState struct {
}

func (ResourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceState)(nil)).Elem()
}

type resourceArgs struct {
	Boolean     bool            `codeinfra:"boolean"`
	BooleanMap  map[string]bool `codeinfra:"booleanMap"`
	Float       float64         `codeinfra:"float"`
	Integer     int             `codeinfra:"integer"`
	NumberArray []float64       `codeinfra:"numberArray"`
	String      string          `codeinfra:"string"`
}

// The set of arguments for constructing a Resource resource.
type ResourceArgs struct {
	Boolean     codeinfra.BoolInput
	BooleanMap  codeinfra.BoolMapInput
	Float       codeinfra.Float64Input
	Integer     codeinfra.IntInput
	NumberArray codeinfra.Float64ArrayInput
	String      codeinfra.StringInput
}

func (ResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceArgs)(nil)).Elem()
}

type ResourceInput interface {
	codeinfra.Input

	ToResourceOutput() ResourceOutput
	ToResourceOutputWithContext(ctx context.Context) ResourceOutput
}

func (*Resource) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (i *Resource) ToResourceOutput() ResourceOutput {
	return i.ToResourceOutputWithContext(context.Background())
}

func (i *Resource) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(ResourceOutput)
}

type ResourceOutput struct{ *codeinfra.OutputState }

func (ResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (o ResourceOutput) ToResourceOutput() ResourceOutput {
	return o
}

func (o ResourceOutput) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return o
}

func (o ResourceOutput) Boolean() codeinfra.BoolOutput {
	return o.ApplyT(func(v *Resource) codeinfra.BoolOutput { return v.Boolean }).(codeinfra.BoolOutput)
}

func (o ResourceOutput) BooleanMap() codeinfra.BoolMapOutput {
	return o.ApplyT(func(v *Resource) codeinfra.BoolMapOutput { return v.BooleanMap }).(codeinfra.BoolMapOutput)
}

func (o ResourceOutput) Float() codeinfra.Float64Output {
	return o.ApplyT(func(v *Resource) codeinfra.Float64Output { return v.Float }).(codeinfra.Float64Output)
}

func (o ResourceOutput) Integer() codeinfra.IntOutput {
	return o.ApplyT(func(v *Resource) codeinfra.IntOutput { return v.Integer }).(codeinfra.IntOutput)
}

func (o ResourceOutput) NumberArray() codeinfra.Float64ArrayOutput {
	return o.ApplyT(func(v *Resource) codeinfra.Float64ArrayOutput { return v.NumberArray }).(codeinfra.Float64ArrayOutput)
}

func (o ResourceOutput) String() codeinfra.StringOutput {
	return o.ApplyT(func(v *Resource) codeinfra.StringOutput { return v.String }).(codeinfra.StringOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*ResourceInput)(nil)).Elem(), &Resource{})
	codeinfra.RegisterOutputType(ResourceOutput{})
}
