# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from ... import meta as _meta

__all__ = ['ConfigMapInitArgs', 'ConfigMap']

@codeinfra.input_type
class ConfigMapInitArgs:
    def __init__(__self__, *,
                 api_version: Optional[codeinfra.Input[str]] = None,
                 binary_data: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]] = None,
                 data: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]] = None,
                 immutable: Optional[codeinfra.Input[bool]] = None,
                 kind: Optional[codeinfra.Input[str]] = None,
                 metadata: Optional[codeinfra.Input['_meta.v1.ObjectMetaArgs']] = None):
        """
        The set of arguments for constructing a ConfigMap resource.
        :param codeinfra.Input[str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param codeinfra.Input[Mapping[str, codeinfra.Input[str]]] binary_data: BinaryData contains the binary data. Each key must consist of alphanumeric characters, '-', '_' or '.'. BinaryData can contain byte sequences that are not in the UTF-8 range. The keys stored in BinaryData must not overlap with the ones in the Data field, this is enforced during validation process. Using this field will require 1.10+ apiserver and kubelet.
        :param codeinfra.Input[Mapping[str, codeinfra.Input[str]]] data: Data contains the configuration data. Each key must consist of alphanumeric characters, '-', '_' or '.'. Values with non-UTF-8 byte sequences must use the BinaryData field. The keys stored in Data must not overlap with the keys in the BinaryData field, this is enforced during validation process.
        :param codeinfra.Input[bool] immutable: Immutable, if set to true, ensures that data stored in the ConfigMap cannot be updated (only object metadata can be modified). If not set to true, the field can be modified at any time. Defaulted to nil.
        :param codeinfra.Input[str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param codeinfra.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        if api_version is not None:
            codeinfra.set(__self__, "api_version", 'v1')
        if binary_data is not None:
            codeinfra.set(__self__, "binary_data", binary_data)
        if data is not None:
            codeinfra.set(__self__, "data", data)
        if immutable is not None:
            codeinfra.set(__self__, "immutable", immutable)
        if kind is not None:
            codeinfra.set(__self__, "kind", 'ConfigMap')
        if metadata is not None:
            codeinfra.set(__self__, "metadata", metadata)

    @property
    @codeinfra.getter(name="apiVersion")
    def api_version(self) -> Optional[codeinfra.Input[str]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return codeinfra.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: Optional[codeinfra.Input[str]]):
        codeinfra.set(self, "api_version", value)

    @property
    @codeinfra.getter(name="binaryData")
    def binary_data(self) -> Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]]:
        """
        BinaryData contains the binary data. Each key must consist of alphanumeric characters, '-', '_' or '.'. BinaryData can contain byte sequences that are not in the UTF-8 range. The keys stored in BinaryData must not overlap with the ones in the Data field, this is enforced during validation process. Using this field will require 1.10+ apiserver and kubelet.
        """
        return codeinfra.get(self, "binary_data")

    @binary_data.setter
    def binary_data(self, value: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]]):
        codeinfra.set(self, "binary_data", value)

    @property
    @codeinfra.getter
    def data(self) -> Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]]:
        """
        Data contains the configuration data. Each key must consist of alphanumeric characters, '-', '_' or '.'. Values with non-UTF-8 byte sequences must use the BinaryData field. The keys stored in Data must not overlap with the keys in the BinaryData field, this is enforced during validation process.
        """
        return codeinfra.get(self, "data")

    @data.setter
    def data(self, value: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]]):
        codeinfra.set(self, "data", value)

    @property
    @codeinfra.getter
    def immutable(self) -> Optional[codeinfra.Input[bool]]:
        """
        Immutable, if set to true, ensures that data stored in the ConfigMap cannot be updated (only object metadata can be modified). If not set to true, the field can be modified at any time. Defaulted to nil.
        """
        return codeinfra.get(self, "immutable")

    @immutable.setter
    def immutable(self, value: Optional[codeinfra.Input[bool]]):
        codeinfra.set(self, "immutable", value)

    @property
    @codeinfra.getter
    def kind(self) -> Optional[codeinfra.Input[str]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return codeinfra.get(self, "kind")

    @kind.setter
    def kind(self, value: Optional[codeinfra.Input[str]]):
        codeinfra.set(self, "kind", value)

    @property
    @codeinfra.getter
    def metadata(self) -> Optional[codeinfra.Input['_meta.v1.ObjectMetaArgs']]:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return codeinfra.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[codeinfra.Input['_meta.v1.ObjectMetaArgs']]):
        codeinfra.set(self, "metadata", value)


class ConfigMap(codeinfra.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 api_version: Optional[codeinfra.Input[str]] = None,
                 binary_data: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]] = None,
                 data: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]] = None,
                 immutable: Optional[codeinfra.Input[bool]] = None,
                 kind: Optional[codeinfra.Input[str]] = None,
                 metadata: Optional[codeinfra.Input[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']]] = None,
                 __props__=None):
        """
        A non-overlay, non-component, Kubernetes resource.

        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        :param codeinfra.Input[str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param codeinfra.Input[Mapping[str, codeinfra.Input[str]]] binary_data: BinaryData contains the binary data. Each key must consist of alphanumeric characters, '-', '_' or '.'. BinaryData can contain byte sequences that are not in the UTF-8 range. The keys stored in BinaryData must not overlap with the ones in the Data field, this is enforced during validation process. Using this field will require 1.10+ apiserver and kubelet.
        :param codeinfra.Input[Mapping[str, codeinfra.Input[str]]] data: Data contains the configuration data. Each key must consist of alphanumeric characters, '-', '_' or '.'. Values with non-UTF-8 byte sequences must use the BinaryData field. The keys stored in Data must not overlap with the keys in the BinaryData field, this is enforced during validation process.
        :param codeinfra.Input[bool] immutable: Immutable, if set to true, ensures that data stored in the ConfigMap cannot be updated (only object metadata can be modified). If not set to true, the field can be modified at any time. Defaulted to nil.
        :param codeinfra.Input[str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param codeinfra.Input[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ConfigMapInitArgs] = None,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        A non-overlay, non-component, Kubernetes resource.

        :param str resource_name: The name of the resource.
        :param ConfigMapInitArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConfigMapInitArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 api_version: Optional[codeinfra.Input[str]] = None,
                 binary_data: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]] = None,
                 data: Optional[codeinfra.Input[Mapping[str, codeinfra.Input[str]]]] = None,
                 immutable: Optional[codeinfra.Input[bool]] = None,
                 kind: Optional[codeinfra.Input[str]] = None,
                 metadata: Optional[codeinfra.Input[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConfigMapInitArgs.__new__(ConfigMapInitArgs)

            __props__.__dict__["api_version"] = 'v1'
            __props__.__dict__["binary_data"] = binary_data
            __props__.__dict__["data"] = data
            __props__.__dict__["immutable"] = immutable
            __props__.__dict__["kind"] = 'ConfigMap'
            __props__.__dict__["metadata"] = metadata
        super(ConfigMap, __self__).__init__(
            'kubernetes:core/v1:ConfigMap',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: codeinfra.Input[str],
            opts: Optional[codeinfra.ResourceOptions] = None) -> 'ConfigMap':
        """
        Get an existing ConfigMap resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param codeinfra.Input[str] id: The unique provider ID of the resource to lookup.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        opts = codeinfra.ResourceOptions.merge(opts, codeinfra.ResourceOptions(id=id))

        __props__ = ConfigMapInitArgs.__new__(ConfigMapInitArgs)

        __props__.__dict__["api_version"] = None
        __props__.__dict__["binary_data"] = None
        __props__.__dict__["data"] = None
        __props__.__dict__["immutable"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["metadata"] = None
        return ConfigMap(resource_name, opts=opts, __props__=__props__)

    @property
    @codeinfra.getter(name="apiVersion")
    def api_version(self) -> codeinfra.Output[str]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return codeinfra.get(self, "api_version")

    @property
    @codeinfra.getter(name="binaryData")
    def binary_data(self) -> codeinfra.Output[Mapping[str, str]]:
        """
        BinaryData contains the binary data. Each key must consist of alphanumeric characters, '-', '_' or '.'. BinaryData can contain byte sequences that are not in the UTF-8 range. The keys stored in BinaryData must not overlap with the ones in the Data field, this is enforced during validation process. Using this field will require 1.10+ apiserver and kubelet.
        """
        return codeinfra.get(self, "binary_data")

    @property
    @codeinfra.getter
    def data(self) -> codeinfra.Output[Mapping[str, str]]:
        """
        Data contains the configuration data. Each key must consist of alphanumeric characters, '-', '_' or '.'. Values with non-UTF-8 byte sequences must use the BinaryData field. The keys stored in Data must not overlap with the keys in the BinaryData field, this is enforced during validation process.
        """
        return codeinfra.get(self, "data")

    @property
    @codeinfra.getter
    def immutable(self) -> codeinfra.Output[bool]:
        """
        Immutable, if set to true, ensures that data stored in the ConfigMap cannot be updated (only object metadata can be modified). If not set to true, the field can be modified at any time. Defaulted to nil.
        """
        return codeinfra.get(self, "immutable")

    @property
    @codeinfra.getter
    def kind(self) -> codeinfra.Output[str]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return codeinfra.get(self, "kind")

    @property
    @codeinfra.getter
    def metadata(self) -> codeinfra.Output['_meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return codeinfra.get(self, "metadata")

