# coding=utf-8
# *** WARNING: this file was generated by codeinfra-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .goodbye import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "goodbye",
  "mod": "index",
  "fqn": "codeinfra_goodbye",
  "classes": {
   "goodbye:index:Goodbye": "Goodbye"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "goodbye",
  "token": "codeinfra:providers:goodbye",
  "fqn": "codeinfra_goodbye",
  "class": "Provider"
 }
]
"""
)
