// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "../utilities";

import * as codeinfraGoogleNative from "@codeinfra/google-native";

export class IamResource extends codeinfra.ComponentResource {
    /** @internal */
    public static readonly __codeinfraType = 'example:myModule:IamResource';

    /**
     * Returns true if the given object is an instance of IamResource.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IamResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === IamResource.__codeinfraType;
    }


    /**
     * Create a IamResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IamResourceArgs, opts?: codeinfra.ComponentResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["config"] = args ? args.config : undefined;
        } else {
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IamResource.__codeinfraType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a IamResource resource.
 */
export interface IamResourceArgs {
    config?: codeinfra.Input<codeinfraGoogleNative.types.input.iam.v1.AuditConfigArgs>;
}
