# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import gcp as _gcp
import codeinfra_google_native

__all__ = ['ReplicatedBucketArgs', 'ReplicatedBucket']

@codeinfra.input_type
class ReplicatedBucketArgs:
    def __init__(__self__, *,
                 destination_region: codeinfra.Input[str]):
        """
        The set of arguments for constructing a ReplicatedBucket resource.
        :param codeinfra.Input[str] destination_region: Region to which data should be replicated.
        """
        codeinfra.set(__self__, "destination_region", destination_region)

    @property
    @codeinfra.getter(name="destinationRegion")
    def destination_region(self) -> codeinfra.Input[str]:
        """
        Region to which data should be replicated.
        """
        return codeinfra.get(self, "destination_region")

    @destination_region.setter
    def destination_region(self, value: codeinfra.Input[str]):
        codeinfra.set(self, "destination_region", value)


class ReplicatedBucket(codeinfra.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 destination_region: Optional[codeinfra.Input[str]] = None,
                 __props__=None):
        """
        Create a ReplicatedBucket resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        :param codeinfra.Input[str] destination_region: Region to which data should be replicated.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ReplicatedBucketArgs,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        Create a ReplicatedBucket resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ReplicatedBucketArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ReplicatedBucketArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 destination_region: Optional[codeinfra.Input[str]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ReplicatedBucketArgs.__new__(ReplicatedBucketArgs)

            if destination_region is None and not opts.urn:
                raise TypeError("Missing required property 'destination_region'")
            __props__.__dict__["destination_region"] = destination_region
            __props__.__dict__["location_policy"] = None
        super(ReplicatedBucket, __self__).__init__(
            'example:index:ReplicatedBucket',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @codeinfra.getter(name="locationPolicy")
    def location_policy(self) -> codeinfra.Output[Optional['_gcp.gke.outputs.NodePoolAutoscaling']]:
        """
        test stuff
        """
        return codeinfra.get(self, "location_policy")

