// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package different

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"simple-plain-schema-with-root-package/internal"
)

var _ = internal.GetEnvOrDefault

type Foo struct {
	A bool    `codeinfra:"a"`
	B *bool   `codeinfra:"b"`
	C int     `codeinfra:"c"`
	D *int    `codeinfra:"d"`
	E string  `codeinfra:"e"`
	F *string `codeinfra:"f"`
}

// FooInput is an input type that accepts FooArgs and FooOutput values.
// You can construct a concrete instance of `FooInput` via:
//
//	FooArgs{...}
type FooInput interface {
	codeinfra.Input

	ToFooOutput() FooOutput
	ToFooOutputWithContext(context.Context) FooOutput
}

type FooArgs struct {
	A bool    `codeinfra:"a"`
	B *bool   `codeinfra:"b"`
	C int     `codeinfra:"c"`
	D *int    `codeinfra:"d"`
	E string  `codeinfra:"e"`
	F *string `codeinfra:"f"`
}

func (FooArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Foo)(nil)).Elem()
}

func (i FooArgs) ToFooOutput() FooOutput {
	return i.ToFooOutputWithContext(context.Background())
}

func (i FooArgs) ToFooOutputWithContext(ctx context.Context) FooOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(FooOutput)
}

func (i FooArgs) ToFooPtrOutput() FooPtrOutput {
	return i.ToFooPtrOutputWithContext(context.Background())
}

func (i FooArgs) ToFooPtrOutputWithContext(ctx context.Context) FooPtrOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(FooOutput).ToFooPtrOutputWithContext(ctx)
}

// FooPtrInput is an input type that accepts FooArgs, FooPtr and FooPtrOutput values.
// You can construct a concrete instance of `FooPtrInput` via:
//
//	        FooArgs{...}
//
//	or:
//
//	        nil
type FooPtrInput interface {
	codeinfra.Input

	ToFooPtrOutput() FooPtrOutput
	ToFooPtrOutputWithContext(context.Context) FooPtrOutput
}

type fooPtrType FooArgs

func FooPtr(v *FooArgs) FooPtrInput {
	return (*fooPtrType)(v)
}

func (*fooPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Foo)(nil)).Elem()
}

func (i *fooPtrType) ToFooPtrOutput() FooPtrOutput {
	return i.ToFooPtrOutputWithContext(context.Background())
}

func (i *fooPtrType) ToFooPtrOutputWithContext(ctx context.Context) FooPtrOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(FooPtrOutput)
}

// FooArrayInput is an input type that accepts FooArray and FooArrayOutput values.
// You can construct a concrete instance of `FooArrayInput` via:
//
//	FooArray{ FooArgs{...} }
type FooArrayInput interface {
	codeinfra.Input

	ToFooArrayOutput() FooArrayOutput
	ToFooArrayOutputWithContext(context.Context) FooArrayOutput
}

type FooArray []FooInput

func (FooArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Foo)(nil)).Elem()
}

func (i FooArray) ToFooArrayOutput() FooArrayOutput {
	return i.ToFooArrayOutputWithContext(context.Background())
}

func (i FooArray) ToFooArrayOutputWithContext(ctx context.Context) FooArrayOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(FooArrayOutput)
}

type FooOutput struct{ *codeinfra.OutputState }

func (FooOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Foo)(nil)).Elem()
}

func (o FooOutput) ToFooOutput() FooOutput {
	return o
}

func (o FooOutput) ToFooOutputWithContext(ctx context.Context) FooOutput {
	return o
}

func (o FooOutput) ToFooPtrOutput() FooPtrOutput {
	return o.ToFooPtrOutputWithContext(context.Background())
}

func (o FooOutput) ToFooPtrOutputWithContext(ctx context.Context) FooPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Foo) *Foo {
		return &v
	}).(FooPtrOutput)
}

func (o FooOutput) A() codeinfra.BoolOutput {
	return o.ApplyT(func(v Foo) bool { return v.A }).(codeinfra.BoolOutput)
}

func (o FooOutput) B() codeinfra.BoolPtrOutput {
	return o.ApplyT(func(v Foo) *bool { return v.B }).(codeinfra.BoolPtrOutput)
}

func (o FooOutput) C() codeinfra.IntOutput {
	return o.ApplyT(func(v Foo) int { return v.C }).(codeinfra.IntOutput)
}

func (o FooOutput) D() codeinfra.IntPtrOutput {
	return o.ApplyT(func(v Foo) *int { return v.D }).(codeinfra.IntPtrOutput)
}

func (o FooOutput) E() codeinfra.StringOutput {
	return o.ApplyT(func(v Foo) string { return v.E }).(codeinfra.StringOutput)
}

func (o FooOutput) F() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v Foo) *string { return v.F }).(codeinfra.StringPtrOutput)
}

type FooPtrOutput struct{ *codeinfra.OutputState }

func (FooPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Foo)(nil)).Elem()
}

func (o FooPtrOutput) ToFooPtrOutput() FooPtrOutput {
	return o
}

func (o FooPtrOutput) ToFooPtrOutputWithContext(ctx context.Context) FooPtrOutput {
	return o
}

func (o FooPtrOutput) Elem() FooOutput {
	return o.ApplyT(func(v *Foo) Foo {
		if v != nil {
			return *v
		}
		var ret Foo
		return ret
	}).(FooOutput)
}

func (o FooPtrOutput) A() codeinfra.BoolPtrOutput {
	return o.ApplyT(func(v *Foo) *bool {
		if v == nil {
			return nil
		}
		return &v.A
	}).(codeinfra.BoolPtrOutput)
}

func (o FooPtrOutput) B() codeinfra.BoolPtrOutput {
	return o.ApplyT(func(v *Foo) *bool {
		if v == nil {
			return nil
		}
		return v.B
	}).(codeinfra.BoolPtrOutput)
}

func (o FooPtrOutput) C() codeinfra.IntPtrOutput {
	return o.ApplyT(func(v *Foo) *int {
		if v == nil {
			return nil
		}
		return &v.C
	}).(codeinfra.IntPtrOutput)
}

func (o FooPtrOutput) D() codeinfra.IntPtrOutput {
	return o.ApplyT(func(v *Foo) *int {
		if v == nil {
			return nil
		}
		return v.D
	}).(codeinfra.IntPtrOutput)
}

func (o FooPtrOutput) E() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v *Foo) *string {
		if v == nil {
			return nil
		}
		return &v.E
	}).(codeinfra.StringPtrOutput)
}

func (o FooPtrOutput) F() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v *Foo) *string {
		if v == nil {
			return nil
		}
		return v.F
	}).(codeinfra.StringPtrOutput)
}

type FooArrayOutput struct{ *codeinfra.OutputState }

func (FooArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Foo)(nil)).Elem()
}

func (o FooArrayOutput) ToFooArrayOutput() FooArrayOutput {
	return o
}

func (o FooArrayOutput) ToFooArrayOutputWithContext(ctx context.Context) FooArrayOutput {
	return o
}

func (o FooArrayOutput) Index(i codeinfra.IntInput) FooOutput {
	return codeinfra.All(o, i).ApplyT(func(vs []interface{}) Foo {
		return vs[0].([]Foo)[vs[1].(int)]
	}).(FooOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*FooInput)(nil)).Elem(), FooArgs{})
	codeinfra.RegisterInputType(reflect.TypeOf((*FooPtrInput)(nil)).Elem(), FooArgs{})
	codeinfra.RegisterInputType(reflect.TypeOf((*FooArrayInput)(nil)).Elem(), FooArray{})
	codeinfra.RegisterOutputType(FooOutput{})
	codeinfra.RegisterOutputType(FooPtrOutput{})
	codeinfra.RegisterOutputType(FooArrayOutput{})
}
