// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package different

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"simple-plain-schema-with-root-package/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *codeinfra.Context, name, typ, urn string) (r codeinfra.Resource, err error) {
	switch typ {
	case "example::Component":
		r = &Component{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, codeinfra.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *codeinfra.Context, name, typ, urn string) (codeinfra.ProviderResource, error) {
	if typ != "codeinfra:providers:example" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, codeinfra.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	codeinfra.RegisterResourceModule(
		"example",
		"",
		&module{version},
	)
	codeinfra.RegisterResourcePackage(
		"example",
		&pkg{version},
	)
}
