// *** WARNING: this file was generated by codeinfra-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ResourceArgs } from "./resource";
export type Resource = import("./resource").Resource;
export const Resource: typeof import("./resource").Resource = null as any;
utilities.lazyLoad(exports, ["Resource"], () => require("./resource"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): codeinfra.Resource => {
        switch (type) {
            case "alpha:index:Resource":
                return new Resource(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
codeinfra.runtime.registerResourceModule("alpha", "index", _module)
codeinfra.runtime.registerResourcePackage("alpha", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): codeinfra.ProviderResource => {
        if (type !== "codeinfra:providers:alpha") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
