// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"regress-8403/mongodbatlas/internal"
)

func LookupCustomDbRoles(ctx *codeinfra.Context, args *LookupCustomDbRolesArgs, opts ...codeinfra.InvokeOption) (*LookupCustomDbRolesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCustomDbRolesResult
	err := ctx.Invoke("mongodbatlas::getCustomDbRoles", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupCustomDbRolesArgs struct {
}

type LookupCustomDbRolesResult struct {
	Result *GetCustomDbRolesResult `codeinfra:"result"`
}

func LookupCustomDbRolesOutput(ctx *codeinfra.Context, args LookupCustomDbRolesOutputArgs, opts ...codeinfra.InvokeOption) LookupCustomDbRolesResultOutput {
	return codeinfra.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupCustomDbRolesResultOutput, error) {
			args := v.(LookupCustomDbRolesArgs)
			options := codeinfra.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mongodbatlas::getCustomDbRoles", args, LookupCustomDbRolesResultOutput{}, options).(LookupCustomDbRolesResultOutput), nil
		}).(LookupCustomDbRolesResultOutput)
}

type LookupCustomDbRolesOutputArgs struct {
}

func (LookupCustomDbRolesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCustomDbRolesArgs)(nil)).Elem()
}

type LookupCustomDbRolesResultOutput struct{ *codeinfra.OutputState }

func (LookupCustomDbRolesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCustomDbRolesResult)(nil)).Elem()
}

func (o LookupCustomDbRolesResultOutput) ToLookupCustomDbRolesResultOutput() LookupCustomDbRolesResultOutput {
	return o
}

func (o LookupCustomDbRolesResultOutput) ToLookupCustomDbRolesResultOutputWithContext(ctx context.Context) LookupCustomDbRolesResultOutput {
	return o
}

func (o LookupCustomDbRolesResultOutput) Result() GetCustomDbRolesResultPtrOutput {
	return o.ApplyT(func(v LookupCustomDbRolesResult) *GetCustomDbRolesResult { return v.Result }).(GetCustomDbRolesResultPtrOutput)
}

func init() {
	codeinfra.RegisterOutputType(LookupCustomDbRolesResultOutput{})
}
