# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'MyOutputType',
]

@codeinfra.output_type
class MyOutputType(dict):
    def __init__(__self__, *,
                 some_result: str):
        codeinfra.set(__self__, "some_result", some_result)

    @property
    @codeinfra.getter(name="someResult")
    def some_result(self) -> str:
        return codeinfra.get(self, "some_result")


