// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

import * as codeinfraAws from "@codeinfra/aws";

export class StaticPage extends codeinfra.ComponentResource {
    /** @internal */
    public static readonly __codeinfraType = 'xyz:index:StaticPage';

    /**
     * Returns true if the given object is an instance of StaticPage.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StaticPage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === StaticPage.__codeinfraType;
    }

    /**
     * The bucket resource.
     */
    public /*out*/ readonly bucket!: codeinfra.Output<codeinfraAws.s3.Bucket>;
    /**
     * The website URL.
     */
    public /*out*/ readonly websiteUrl!: codeinfra.Output<string>;

    /**
     * Create a StaticPage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StaticPageArgs, opts?: codeinfra.ComponentResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.indexContent === undefined) && !opts.urn) {
                throw new Error("Missing required property 'indexContent'");
            }
            resourceInputs["foo"] = args ? args.foo : undefined;
            resourceInputs["indexContent"] = args ? args.indexContent : undefined;
            resourceInputs["bucket"] = undefined /*out*/;
            resourceInputs["websiteUrl"] = undefined /*out*/;
        } else {
            resourceInputs["bucket"] = undefined /*out*/;
            resourceInputs["websiteUrl"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StaticPage.__codeinfraType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a StaticPage resource.
 */
export interface StaticPageArgs {
    foo?: inputs.FooArgs;
    /**
     * The HTML content for index.html.
     */
    indexContent: codeinfra.Input<string>;
}
