// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package repro

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"go-plain-ref-repro/repro/internal"
)

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *codeinfra.Context, name, typ, urn string) (codeinfra.ProviderResource, error) {
	if typ != "codeinfra:providers:repro" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, codeinfra.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	codeinfra.RegisterResourcePackage(
		"repro",
		&pkg{version},
	)
}
