// Code generated by codeinfra-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"errors"
	"example.com/codeinfra-config/sdk/go/v9/config/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

type Resource struct {
	codeinfra.CustomResourceState

	Text codeinfra.StringOutput `codeinfra:"text"`
}

// NewResource registers a new resource with the given unique name, arguments, and options.
func NewResource(ctx *codeinfra.Context,
	name string, args *ResourceArgs, opts ...codeinfra.ResourceOption) (*Resource, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Text == nil {
		return nil, errors.New("invalid value for required argument 'Text'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Resource
	err := ctx.RegisterResource("config:index:Resource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResource gets an existing Resource resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResource(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *ResourceState, opts ...codeinfra.ResourceOption) (*Resource, error) {
	var resource Resource
	err := ctx.ReadResource("config:index:Resource", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Resource resources.
type resourceState struct {
}

type ResourceState struct {
}

func (ResourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceState)(nil)).Elem()
}

type resourceArgs struct {
	Text string `codeinfra:"text"`
}

// The set of arguments for constructing a Resource resource.
type ResourceArgs struct {
	Text codeinfra.StringInput
}

func (ResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceArgs)(nil)).Elem()
}

type ResourceInput interface {
	codeinfra.Input

	ToResourceOutput() ResourceOutput
	ToResourceOutputWithContext(ctx context.Context) ResourceOutput
}

func (*Resource) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (i *Resource) ToResourceOutput() ResourceOutput {
	return i.ToResourceOutputWithContext(context.Background())
}

func (i *Resource) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(ResourceOutput)
}

type ResourceOutput struct{ *codeinfra.OutputState }

func (ResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (o ResourceOutput) ToResourceOutput() ResourceOutput {
	return o
}

func (o ResourceOutput) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return o
}

func (o ResourceOutput) Text() codeinfra.StringOutput {
	return o.ApplyT(func(v *Resource) codeinfra.StringOutput { return v.Text }).(codeinfra.StringOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*ResourceInput)(nil)).Elem(), &Resource{})
	codeinfra.RegisterOutputType(ResourceOutput{})
}
