// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"assets-and-archives-go-generics-only/example/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
)

func GetAssets(ctx *codeinfra.Context, args *GetAssetsArgs, opts ...codeinfra.InvokeOption) (*GetAssetsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAssetsResult
	err := ctx.Invoke("example::GetAssets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAssetsArgs struct {
	Archive codeinfra.Archive        `codeinfra:"archive"`
	Source  codeinfra.AssetOrArchive `codeinfra:"source"`
}

type GetAssetsResult struct {
	Archive codeinfra.Archive        `codeinfra:"archive"`
	Source  codeinfra.AssetOrArchive `codeinfra:"source"`
}

func GetAssetsOutput(ctx *codeinfra.Context, args GetAssetsOutputArgs, opts ...codeinfra.InvokeOption) GetAssetsResultOutput {
	outputResult := codeinfrax.ApplyErr[*GetAssetsArgs](args.ToOutput(), func(plainArgs *GetAssetsArgs) (*GetAssetsResult, error) {
		return GetAssets(ctx, plainArgs, opts...)
	})

	return codeinfrax.Cast[GetAssetsResultOutput, *GetAssetsResult](outputResult)
}

type GetAssetsOutputArgs struct {
	Archive codeinfrax.Input[codeinfra.Archive]        `codeinfra:"archive"`
	Source  codeinfrax.Input[codeinfra.AssetOrArchive] `codeinfra:"source"`
}

func (args GetAssetsOutputArgs) ToOutput() codeinfrax.Output[*GetAssetsArgs] {
	allArgs := codeinfrax.All(
		args.Archive.ToOutput(context.Background()).AsAny(),
		args.Source.ToOutput(context.Background()).AsAny())
	return codeinfrax.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *GetAssetsArgs {
		return &GetAssetsArgs{
			Archive: resolvedArgs[0].(codeinfra.Archive),
			Source:  resolvedArgs[1].(codeinfra.AssetOrArchive),
		}
	})
}

type GetAssetsResultOutput struct{ *codeinfra.OutputState }

func (GetAssetsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAssetsResult)(nil)).Elem()
}

func (o GetAssetsResultOutput) ToOutput(context.Context) codeinfrax.Output[*GetAssetsResult] {
	return codeinfrax.Output[*GetAssetsResult]{
		OutputState: o.OutputState,
	}
}

func (o GetAssetsResultOutput) Archive() codeinfrax.Output[codeinfra.Archive] {
	return codeinfrax.Apply[*GetAssetsResult](o, func(v *GetAssetsResult) codeinfra.Archive { return v.Archive })
}

func (o GetAssetsResultOutput) Source() codeinfrax.Output[codeinfra.AssetOrArchive] {
	return codeinfrax.Apply[*GetAssetsResult](o, func(v *GetAssetsResult) codeinfra.AssetOrArchive { return v.Source })
}
