// *** WARNING: this file was generated by codeinfra-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { StringArgs } from "./string";
export type String = import("./string").String;
export const String: typeof import("./string").String = null as any;
utilities.lazyLoad(exports, ["String"], () => require("./string"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): codeinfra.Resource => {
        switch (type) {
            case "large:index:String":
                return new String(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
codeinfra.runtime.registerResourceModule("large", "index", _module)
codeinfra.runtime.registerResourcePackage("large", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): codeinfra.ProviderResource => {
        if (type !== "codeinfra:providers:large") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
