// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Codeinfra.Serialization;

namespace Codeinfra.Example.Inputs
{

    public sealed class SomeOtherObjectArgs : global::Codeinfra.ResourceArgs
    {
        [Input("baz")]
        public Input<string>? Baz { get; set; }

        public SomeOtherObjectArgs()
        {
        }
        public static new SomeOtherObjectArgs Empty => new SomeOtherObjectArgs();
    }
}
