// *** WARNING: this file was generated by codeinfra-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

export class ArchiveResource extends codeinfra.CustomResource {
    /**
     * Get an existing ArchiveResource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: codeinfra.Input<codeinfra.ID>, opts?: codeinfra.CustomResourceOptions): ArchiveResource {
        return new ArchiveResource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __codeinfraType = 'asset-archive:index:ArchiveResource';

    /**
     * Returns true if the given object is an instance of ArchiveResource.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ArchiveResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === ArchiveResource.__codeinfraType;
    }

    public readonly value!: codeinfra.Output<codeinfra.asset.Archive>;

    /**
     * Create a ArchiveResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ArchiveResourceArgs, opts?: codeinfra.CustomResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["value"] = args ? args.value : undefined;
        } else {
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ArchiveResource.__codeinfraType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ArchiveResource resource.
 */
export interface ArchiveResourceArgs {
    value: codeinfra.Input<codeinfra.asset.Archive>;
}
