// Code generated by codeinfra-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package simpleinvoke

import (
	"context"
	"reflect"

	"example.com/codeinfra-simple-invoke/sdk/go/v10/simpleinvoke/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

func MyInvoke(ctx *codeinfra.Context, args *MyInvokeArgs, opts ...codeinfra.InvokeOption) (*MyInvokeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv MyInvokeResult
	err := ctx.Invoke("simple-invoke:index:myInvoke", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type MyInvokeArgs struct {
	Value string `codeinfra:"value"`
}

type MyInvokeResult struct {
	Result string `codeinfra:"result"`
}

func MyInvokeOutput(ctx *codeinfra.Context, args MyInvokeOutputArgs, opts ...codeinfra.InvokeOption) MyInvokeResultOutput {
	return codeinfra.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (MyInvokeResultOutput, error) {
			args := v.(MyInvokeArgs)
			options := codeinfra.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("simple-invoke:index:myInvoke", args, MyInvokeResultOutput{}, options).(MyInvokeResultOutput), nil
		}).(MyInvokeResultOutput)
}

type MyInvokeOutputArgs struct {
	Value codeinfra.StringInput `codeinfra:"value"`
}

func (MyInvokeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*MyInvokeArgs)(nil)).Elem()
}

type MyInvokeResultOutput struct{ *codeinfra.OutputState }

func (MyInvokeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*MyInvokeResult)(nil)).Elem()
}

func (o MyInvokeResultOutput) ToMyInvokeResultOutput() MyInvokeResultOutput {
	return o
}

func (o MyInvokeResultOutput) ToMyInvokeResultOutputWithContext(ctx context.Context) MyInvokeResultOutput {
	return o
}

func (o MyInvokeResultOutput) Result() codeinfra.StringOutput {
	return o.ApplyT(func(v MyInvokeResult) string { return v.Result }).(codeinfra.StringOutput)
}

func init() {
	codeinfra.RegisterOutputType(MyInvokeResultOutput{})
}
