# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import mod1 as _mod1
from . import mod2 as _mod2
from ._inputs import *

__all__ = ['ModuleTestArgs', 'ModuleTest']

@codeinfra.input_type
class ModuleTestArgs:
    def __init__(__self__, *,
                 mod1: Optional[codeinfra.Input['_mod1.TypArgs']] = None,
                 val: Optional[codeinfra.Input['TypArgs']] = None):
        """
        The set of arguments for constructing a ModuleTest resource.
        """
        if mod1 is not None:
            codeinfra.set(__self__, "mod1", mod1)
        if val is not None:
            codeinfra.set(__self__, "val", val)

    @property
    @codeinfra.getter
    def mod1(self) -> Optional[codeinfra.Input['_mod1.TypArgs']]:
        return codeinfra.get(self, "mod1")

    @mod1.setter
    def mod1(self, value: Optional[codeinfra.Input['_mod1.TypArgs']]):
        codeinfra.set(self, "mod1", value)

    @property
    @codeinfra.getter
    def val(self) -> Optional[codeinfra.Input['TypArgs']]:
        return codeinfra.get(self, "val")

    @val.setter
    def val(self, value: Optional[codeinfra.Input['TypArgs']]):
        codeinfra.set(self, "val", value)


class ModuleTest(codeinfra.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 mod1: Optional[codeinfra.Input[Union['_mod1.TypArgs', '_mod1.TypArgsDict']]] = None,
                 val: Optional[codeinfra.Input[Union['TypArgs', 'TypArgsDict']]] = None,
                 __props__=None):
        """
        Create a ModuleTest resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ModuleTestArgs] = None,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        Create a ModuleTest resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ModuleTestArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ModuleTestArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 mod1: Optional[codeinfra.Input[Union['_mod1.TypArgs', '_mod1.TypArgsDict']]] = None,
                 val: Optional[codeinfra.Input[Union['TypArgs', 'TypArgsDict']]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ModuleTestArgs.__new__(ModuleTestArgs)

            __props__.__dict__["mod1"] = mod1
            __props__.__dict__["val"] = val
        super(ModuleTest, __self__).__init__(
            'example:index:moduleTest',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: codeinfra.Input[str],
            opts: Optional[codeinfra.ResourceOptions] = None) -> 'ModuleTest':
        """
        Get an existing ModuleTest resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param codeinfra.Input[str] id: The unique provider ID of the resource to lookup.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        opts = codeinfra.ResourceOptions.merge(opts, codeinfra.ResourceOptions(id=id))

        __props__ = ModuleTestArgs.__new__(ModuleTestArgs)

        return ModuleTest(resource_name, opts=opts, __props__=__props__)

