# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'Child',
]

@codeinfra.output_type
class Child(dict):
    def __init__(__self__, *,
                 age: Optional[int] = None,
                 name: Optional[str] = None):
        if age is not None:
            codeinfra.set(__self__, "age", age)
        if name is not None:
            codeinfra.set(__self__, "name", name)

    @property
    @codeinfra.getter
    def age(self) -> Optional[int]:
        return codeinfra.get(self, "age")

    @property
    @codeinfra.getter
    def name(self) -> Optional[str]:
        return codeinfra.get(self, "name")


