# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import config as _config
from ._enums import *

__all__ = ['ProviderArgs', 'Provider']

@codeinfra.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 favorite_color: Optional[codeinfra.Input[Union[str, 'Color']]] = None,
                 secret_sandwiches: Optional[codeinfra.Input[Sequence[codeinfra.Input['_config.SandwichArgs']]]] = None):
        """
        The set of arguments for constructing a Provider resource.
        :param codeinfra.Input[Union[str, 'Color']] favorite_color: this is a relaxed string enum which can also be set via env var
        :param codeinfra.Input[Sequence[codeinfra.Input['_config.SandwichArgs']]] secret_sandwiches: Super duper secret sandwiches.
        """
        if favorite_color is None:
            favorite_color = _utilities.get_env('FAVE_COLOR')
        if favorite_color is not None:
            codeinfra.set(__self__, "favorite_color", favorite_color)
        if secret_sandwiches is not None:
            codeinfra.set(__self__, "secret_sandwiches", secret_sandwiches)

    @property
    @codeinfra.getter(name="favoriteColor")
    def favorite_color(self) -> Optional[codeinfra.Input[Union[str, 'Color']]]:
        """
        this is a relaxed string enum which can also be set via env var
        """
        return codeinfra.get(self, "favorite_color")

    @favorite_color.setter
    def favorite_color(self, value: Optional[codeinfra.Input[Union[str, 'Color']]]):
        codeinfra.set(self, "favorite_color", value)

    @property
    @codeinfra.getter(name="secretSandwiches")
    def secret_sandwiches(self) -> Optional[codeinfra.Input[Sequence[codeinfra.Input['_config.SandwichArgs']]]]:
        """
        Super duper secret sandwiches.
        """
        return codeinfra.get(self, "secret_sandwiches")

    @secret_sandwiches.setter
    def secret_sandwiches(self, value: Optional[codeinfra.Input[Sequence[codeinfra.Input['_config.SandwichArgs']]]]):
        codeinfra.set(self, "secret_sandwiches", value)


class Provider(codeinfra.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 favorite_color: Optional[codeinfra.Input[Union[str, 'Color']]] = None,
                 secret_sandwiches: Optional[codeinfra.Input[Sequence[codeinfra.Input[Union['_config.SandwichArgs', '_config.SandwichArgsDict']]]]] = None,
                 __props__=None):
        """
        Create a Configstation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        :param codeinfra.Input[Union[str, 'Color']] favorite_color: this is a relaxed string enum which can also be set via env var
        :param codeinfra.Input[Sequence[codeinfra.Input[Union['_config.SandwichArgs', '_config.SandwichArgsDict']]]] secret_sandwiches: Super duper secret sandwiches.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        Create a Configstation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 favorite_color: Optional[codeinfra.Input[Union[str, 'Color']]] = None,
                 secret_sandwiches: Optional[codeinfra.Input[Sequence[codeinfra.Input[Union['_config.SandwichArgs', '_config.SandwichArgsDict']]]]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if favorite_color is None:
                favorite_color = _utilities.get_env('FAVE_COLOR')
            __props__.__dict__["favorite_color"] = codeinfra.Output.from_input(favorite_color).apply(codeinfra.runtime.to_json) if favorite_color is not None else None
            __props__.__dict__["secret_sandwiches"] = codeinfra.Output.secret(secret_sandwiches).apply(codeinfra.runtime.to_json) if secret_sandwiches is not None else None
        super(Provider, __self__).__init__(
            'configstation',
            resource_name,
            __props__,
            opts)

