# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .foo import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "example",
  "mod": "",
  "fqn": "codeinfra_example",
  "classes": {
   "example::Foo": "Foo"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "example",
  "token": "codeinfra:providers:example",
  "fqn": "codeinfra_example",
  "class": "Provider"
 }
]
"""
)
