// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"assets-and-archives/example/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

func GetAssets(ctx *codeinfra.Context, args *GetAssetsArgs, opts ...codeinfra.InvokeOption) (*GetAssetsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAssetsResult
	err := ctx.Invoke("example::GetAssets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAssetsArgs struct {
	Archive codeinfra.Archive        `codeinfra:"archive"`
	Source  codeinfra.AssetOrArchive `codeinfra:"source"`
}

type GetAssetsResult struct {
	Archive codeinfra.Archive        `codeinfra:"archive"`
	Source  codeinfra.AssetOrArchive `codeinfra:"source"`
}

func GetAssetsOutput(ctx *codeinfra.Context, args GetAssetsOutputArgs, opts ...codeinfra.InvokeOption) GetAssetsResultOutput {
	return codeinfra.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAssetsResultOutput, error) {
			args := v.(GetAssetsArgs)
			options := codeinfra.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("example::GetAssets", args, GetAssetsResultOutput{}, options).(GetAssetsResultOutput), nil
		}).(GetAssetsResultOutput)
}

type GetAssetsOutputArgs struct {
	Archive codeinfra.ArchiveInput        `codeinfra:"archive"`
	Source  codeinfra.AssetOrArchiveInput `codeinfra:"source"`
}

func (GetAssetsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAssetsArgs)(nil)).Elem()
}

type GetAssetsResultOutput struct{ *codeinfra.OutputState }

func (GetAssetsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAssetsResult)(nil)).Elem()
}

func (o GetAssetsResultOutput) ToGetAssetsResultOutput() GetAssetsResultOutput {
	return o
}

func (o GetAssetsResultOutput) ToGetAssetsResultOutputWithContext(ctx context.Context) GetAssetsResultOutput {
	return o
}

func (o GetAssetsResultOutput) Archive() codeinfra.ArchiveOutput {
	return o.ApplyT(func(v GetAssetsResult) codeinfra.Archive { return v.Archive }).(codeinfra.ArchiveOutput)
}

func (o GetAssetsResultOutput) Source() codeinfra.AssetOrArchiveOutput {
	return o.ApplyT(func(v GetAssetsResult) codeinfra.AssetOrArchive { return v.Source }).(codeinfra.AssetOrArchiveOutput)
}

func init() {
	codeinfra.RegisterOutputType(GetAssetsResultOutput{})
}
