// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"output-funcs/mypkg/internal"
)

// n/a
func FuncWithEmptyOutputs(ctx *codeinfra.Context, args *FuncWithEmptyOutputsArgs, opts ...codeinfra.InvokeOption) error {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv struct{}
	err := ctx.Invoke("mypkg::funcWithEmptyOutputs", args, &rv, opts...)
	return err
}

type FuncWithEmptyOutputsArgs struct {
	// The Name of the FeatureGroup.
	Name string `codeinfra:"name"`
}
