// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"output-funcs/mypkg/internal"
)

// Response for all the Bastion Shareable Link endpoints.
// API Version: 2020-11-01.
func GetBastionShareableLink(ctx *codeinfra.Context, args *GetBastionShareableLinkArgs, opts ...codeinfra.InvokeOption) (*GetBastionShareableLinkResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBastionShareableLinkResult
	err := ctx.Invoke("mypkg::getBastionShareableLink", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetBastionShareableLinkArgs struct {
	// The name of the Bastion Host.
	BastionHostName string `codeinfra:"bastionHostName"`
	// The name of the resource group.
	ResourceGroupName string `codeinfra:"resourceGroupName"`
	// List of VM references.
	Vms []BastionShareableLink `codeinfra:"vms"`
}

// Response for all the Bastion Shareable Link endpoints.
type GetBastionShareableLinkResult struct {
	// The URL to get the next set of results.
	NextLink *string `codeinfra:"nextLink"`
}

func GetBastionShareableLinkOutput(ctx *codeinfra.Context, args GetBastionShareableLinkOutputArgs, opts ...codeinfra.InvokeOption) GetBastionShareableLinkResultOutput {
	return codeinfra.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetBastionShareableLinkResultOutput, error) {
			args := v.(GetBastionShareableLinkArgs)
			options := codeinfra.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mypkg::getBastionShareableLink", args, GetBastionShareableLinkResultOutput{}, options).(GetBastionShareableLinkResultOutput), nil
		}).(GetBastionShareableLinkResultOutput)
}

type GetBastionShareableLinkOutputArgs struct {
	// The name of the Bastion Host.
	BastionHostName codeinfra.StringInput `codeinfra:"bastionHostName"`
	// The name of the resource group.
	ResourceGroupName codeinfra.StringInput `codeinfra:"resourceGroupName"`
	// List of VM references.
	Vms BastionShareableLinkArrayInput `codeinfra:"vms"`
}

func (GetBastionShareableLinkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBastionShareableLinkArgs)(nil)).Elem()
}

// Response for all the Bastion Shareable Link endpoints.
type GetBastionShareableLinkResultOutput struct{ *codeinfra.OutputState }

func (GetBastionShareableLinkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBastionShareableLinkResult)(nil)).Elem()
}

func (o GetBastionShareableLinkResultOutput) ToGetBastionShareableLinkResultOutput() GetBastionShareableLinkResultOutput {
	return o
}

func (o GetBastionShareableLinkResultOutput) ToGetBastionShareableLinkResultOutputWithContext(ctx context.Context) GetBastionShareableLinkResultOutput {
	return o
}

func (o GetBastionShareableLinkResultOutput) ToOutput(ctx context.Context) codeinfrax.Output[GetBastionShareableLinkResult] {
	return codeinfrax.Output[GetBastionShareableLinkResult]{
		OutputState: o.OutputState,
	}
}

// The URL to get the next set of results.
func (o GetBastionShareableLinkResultOutput) NextLink() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v GetBastionShareableLinkResult) *string { return v.NextLink }).(codeinfra.StringPtrOutput)
}

func init() {
	codeinfra.RegisterOutputType(GetBastionShareableLinkResultOutput{})
}
