// Code generated by codeinfra-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package secret

import (
	"context"
	"reflect"

	"example.com/codeinfra-secret/sdk/go/v14/secret/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

var _ = internal.GetEnvOrDefault

type Data struct {
	Private string `codeinfra:"private"`
	Public  string `codeinfra:"public"`
}

// DataInput is an input type that accepts DataArgs and DataOutput values.
// You can construct a concrete instance of `DataInput` via:
//
//	DataArgs{...}
type DataInput interface {
	codeinfra.Input

	ToDataOutput() DataOutput
	ToDataOutputWithContext(context.Context) DataOutput
}

type DataArgs struct {
	Private codeinfra.StringInput `codeinfra:"private"`
	Public  codeinfra.StringInput `codeinfra:"public"`
}

func (DataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Data)(nil)).Elem()
}

func (i DataArgs) ToDataOutput() DataOutput {
	return i.ToDataOutputWithContext(context.Background())
}

func (i DataArgs) ToDataOutputWithContext(ctx context.Context) DataOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(DataOutput)
}

type DataOutput struct{ *codeinfra.OutputState }

func (DataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Data)(nil)).Elem()
}

func (o DataOutput) ToDataOutput() DataOutput {
	return o
}

func (o DataOutput) ToDataOutputWithContext(ctx context.Context) DataOutput {
	return o
}

func (o DataOutput) Private() codeinfra.StringOutput {
	return o.ApplyT(func(v Data) string { return v.Private }).(codeinfra.StringOutput)
}

func (o DataOutput) Public() codeinfra.StringOutput {
	return o.ApplyT(func(v Data) string { return v.Public }).(codeinfra.StringOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*DataInput)(nil)).Elem(), DataArgs{})
	codeinfra.RegisterOutputType(DataOutput{})
}
