# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities

__all__ = ['ReleaseArgs', 'Release']

@codeinfra.input_type
class ReleaseArgs:
    def __init__(__self__, *,
                 chart: codeinfra.Input[str],
                 value_yaml_files: Optional[codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]]] = None,
                 values: Optional[codeinfra.Input[Mapping[str, Any]]] = None):
        """
        The set of arguments for constructing a Release resource.
        :param codeinfra.Input[str] chart: Chart name to be installed. A path may be used.
        :param codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]] value_yaml_files: List of assets (raw yaml files). Content is read and merged with values.
        :param codeinfra.Input[Mapping[str, Any]] values: Custom values set for the release.
        """
        codeinfra.set(__self__, "chart", chart)
        if value_yaml_files is not None:
            codeinfra.set(__self__, "value_yaml_files", value_yaml_files)
        if values is not None:
            codeinfra.set(__self__, "values", values)

    @property
    @codeinfra.getter
    def chart(self) -> codeinfra.Input[str]:
        """
        Chart name to be installed. A path may be used.
        """
        return codeinfra.get(self, "chart")

    @chart.setter
    def chart(self, value: codeinfra.Input[str]):
        codeinfra.set(self, "chart", value)

    @property
    @codeinfra.getter(name="valueYamlFiles")
    def value_yaml_files(self) -> Optional[codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]]]:
        """
        List of assets (raw yaml files). Content is read and merged with values.
        """
        return codeinfra.get(self, "value_yaml_files")

    @value_yaml_files.setter
    def value_yaml_files(self, value: Optional[codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]]]):
        codeinfra.set(self, "value_yaml_files", value)

    @property
    @codeinfra.getter
    def values(self) -> Optional[codeinfra.Input[Mapping[str, Any]]]:
        """
        Custom values set for the release.
        """
        return codeinfra.get(self, "values")

    @values.setter
    def values(self, value: Optional[codeinfra.Input[Mapping[str, Any]]]):
        codeinfra.set(self, "values", value)


class Release(codeinfra.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 chart: Optional[codeinfra.Input[str]] = None,
                 value_yaml_files: Optional[codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]]] = None,
                 values: Optional[codeinfra.Input[Mapping[str, Any]]] = None,
                 __props__=None):
        """
        A non-overlay, non-component, non-Kubernetes resource.

        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        :param codeinfra.Input[str] chart: Chart name to be installed. A path may be used.
        :param codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]] value_yaml_files: List of assets (raw yaml files). Content is read and merged with values.
        :param codeinfra.Input[Mapping[str, Any]] values: Custom values set for the release.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ReleaseArgs,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        A non-overlay, non-component, non-Kubernetes resource.

        :param str resource_name: The name of the resource.
        :param ReleaseArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ReleaseArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 chart: Optional[codeinfra.Input[str]] = None,
                 value_yaml_files: Optional[codeinfra.Input[Sequence[codeinfra.Input[Union[codeinfra.Asset, codeinfra.Archive]]]]] = None,
                 values: Optional[codeinfra.Input[Mapping[str, Any]]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ReleaseArgs.__new__(ReleaseArgs)

            if chart is None and not opts.urn:
                raise TypeError("Missing required property 'chart'")
            __props__.__dict__["chart"] = chart
            __props__.__dict__["value_yaml_files"] = value_yaml_files
            __props__.__dict__["values"] = values
        super(Release, __self__).__init__(
            'kubernetes:helm.sh/v3:Release',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: codeinfra.Input[str],
            opts: Optional[codeinfra.ResourceOptions] = None) -> 'Release':
        """
        Get an existing Release resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param codeinfra.Input[str] id: The unique provider ID of the resource to lookup.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        opts = codeinfra.ResourceOptions.merge(opts, codeinfra.ResourceOptions(id=id))

        __props__ = ReleaseArgs.__new__(ReleaseArgs)

        __props__.__dict__["chart"] = None
        __props__.__dict__["value_yaml_files"] = None
        __props__.__dict__["values"] = None
        return Release(resource_name, opts=opts, __props__=__props__)

    @property
    @codeinfra.getter
    def chart(self) -> codeinfra.Output[str]:
        """
        Chart name to be installed. A path may be used.
        """
        return codeinfra.get(self, "chart")

    @property
    @codeinfra.getter(name="valueYamlFiles")
    def value_yaml_files(self) -> codeinfra.Output[Optional[Sequence[Union[codeinfra.Asset, codeinfra.Archive]]]]:
        """
        List of assets (raw yaml files). Content is read and merged with values (with values taking precedence).
        """
        return codeinfra.get(self, "value_yaml_files")

    @property
    @codeinfra.getter
    def values(self) -> codeinfra.Output[Optional[Mapping[str, Any]]]:
        """
        Custom values set for the release.
        """
        return codeinfra.get(self, "values")

