# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import http_module as _http_module
from ._enums import *

__all__ = ['Example_resourceArgs', 'Example_resource']

@codeinfra.input_type
class Example_resourceArgs:
    def __init__(__self__, *,
                 map_enum: Optional[codeinfra.Input[Sequence[codeinfra.Input[Mapping[str, codeinfra.Input['Enum_XYZ']]]]]] = None,
                 request__http: Optional[codeinfra.Input['_http_module.RequestArgs']] = None):
        """
        The set of arguments for constructing a Example_resource resource.
        """
        if map_enum is not None:
            codeinfra.set(__self__, "map_enum", map_enum)
        if request__http is not None:
            codeinfra.set(__self__, "request__http", request__http)

    @property
    @codeinfra.getter
    def map_enum(self) -> Optional[codeinfra.Input[Sequence[codeinfra.Input[Mapping[str, codeinfra.Input['Enum_XYZ']]]]]]:
        return codeinfra.get(self, "map_enum")

    @map_enum.setter
    def map_enum(self, value: Optional[codeinfra.Input[Sequence[codeinfra.Input[Mapping[str, codeinfra.Input['Enum_XYZ']]]]]]):
        codeinfra.set(self, "map_enum", value)

    @property
    @codeinfra.getter(name="request_HTTP")
    def request__http(self) -> Optional[codeinfra.Input['_http_module.RequestArgs']]:
        return codeinfra.get(self, "request__http")

    @request__http.setter
    def request__http(self, value: Optional[codeinfra.Input['_http_module.RequestArgs']]):
        codeinfra.set(self, "request__http", value)


class Example_resource(codeinfra.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 map_enum: Optional[codeinfra.Input[Sequence[codeinfra.Input[Mapping[str, codeinfra.Input['Enum_XYZ']]]]]] = None,
                 request__http: Optional[codeinfra.Input[codeinfra.InputType['_http_module.RequestArgs']]] = None,
                 __props__=None):
        """
        Create a Example_resource resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[Example_resourceArgs] = None,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        Create a Example_resource resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param Example_resourceArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(Example_resourceArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 map_enum: Optional[codeinfra.Input[Sequence[codeinfra.Input[Mapping[str, codeinfra.Input['Enum_XYZ']]]]]] = None,
                 request__http: Optional[codeinfra.Input[codeinfra.InputType['_http_module.RequestArgs']]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = Example_resourceArgs.__new__(Example_resourceArgs)

            __props__.__dict__["map_enum"] = map_enum
            __props__.__dict__["request__http"] = request__http
            __props__.__dict__["url"] = None
            __props__.__dict__["good__urls"] = None
        super(Example_resource, __self__).__init__(
            'legacy_names:index:example_resource',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: codeinfra.Input[str],
            opts: Optional[codeinfra.ResourceOptions] = None) -> 'Example_resource':
        """
        Get an existing Example_resource resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param codeinfra.Input[str] id: The unique provider ID of the resource to lookup.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        opts = codeinfra.ResourceOptions.merge(opts, codeinfra.ResourceOptions(id=id))

        __props__ = Example_resourceArgs.__new__(Example_resourceArgs)

        __props__.__dict__["url"] = None
        __props__.__dict__["good__urls"] = None
        __props__.__dict__["map_enum"] = None
        return Example_resource(resource_name, opts=opts, __props__=__props__)

    @property
    @codeinfra.getter(name="URL")
    def url(self) -> codeinfra.Output[Optional[str]]:
        return codeinfra.get(self, "url")

    @property
    @codeinfra.getter(name="good_URLs")
    def good__urls(self) -> codeinfra.Output[Optional[Sequence[str]]]:
        return codeinfra.get(self, "good__urls")

    @property
    @codeinfra.getter
    def map_enum(self) -> codeinfra.Output[Optional[Sequence[Mapping[str, 'Enum_XYZ']]]]:
        return codeinfra.get(self, "map_enum")

