// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as nested from "./nested";

export {
    nested,
};
codeinfra.runtime.registerResourcePackage("foo", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): codeinfra.ProviderResource => {
        if (type !== "codeinfra:providers:foo") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
