// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

type ExampleEnum string

const (
	ExampleEnumOne = ExampleEnum("one")
	ExampleEnumTwo = ExampleEnum("two")
)

func (ExampleEnum) ElementType() reflect.Type {
	return reflect.TypeOf((*ExampleEnum)(nil)).Elem()
}

func (e ExampleEnum) ToExampleEnumOutput() ExampleEnumOutput {
	return codeinfra.ToOutput(e).(ExampleEnumOutput)
}

func (e ExampleEnum) ToExampleEnumOutputWithContext(ctx context.Context) ExampleEnumOutput {
	return codeinfra.ToOutputWithContext(ctx, e).(ExampleEnumOutput)
}

func (e ExampleEnum) ToExampleEnumPtrOutput() ExampleEnumPtrOutput {
	return e.ToExampleEnumPtrOutputWithContext(context.Background())
}

func (e ExampleEnum) ToExampleEnumPtrOutputWithContext(ctx context.Context) ExampleEnumPtrOutput {
	return ExampleEnum(e).ToExampleEnumOutputWithContext(ctx).ToExampleEnumPtrOutputWithContext(ctx)
}

func (e ExampleEnum) ToStringOutput() codeinfra.StringOutput {
	return codeinfra.ToOutput(codeinfra.String(e)).(codeinfra.StringOutput)
}

func (e ExampleEnum) ToStringOutputWithContext(ctx context.Context) codeinfra.StringOutput {
	return codeinfra.ToOutputWithContext(ctx, codeinfra.String(e)).(codeinfra.StringOutput)
}

func (e ExampleEnum) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return codeinfra.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ExampleEnum) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return codeinfra.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ExampleEnumOutput struct{ *codeinfra.OutputState }

func (ExampleEnumOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ExampleEnum)(nil)).Elem()
}

func (o ExampleEnumOutput) ToExampleEnumOutput() ExampleEnumOutput {
	return o
}

func (o ExampleEnumOutput) ToExampleEnumOutputWithContext(ctx context.Context) ExampleEnumOutput {
	return o
}

func (o ExampleEnumOutput) ToExampleEnumPtrOutput() ExampleEnumPtrOutput {
	return o.ToExampleEnumPtrOutputWithContext(context.Background())
}

func (o ExampleEnumOutput) ToExampleEnumPtrOutputWithContext(ctx context.Context) ExampleEnumPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ExampleEnum) *ExampleEnum {
		return &v
	}).(ExampleEnumPtrOutput)
}

func (o ExampleEnumOutput) ToStringOutput() codeinfra.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ExampleEnumOutput) ToStringOutputWithContext(ctx context.Context) codeinfra.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ExampleEnum) string {
		return string(e)
	}).(codeinfra.StringOutput)
}

func (o ExampleEnumOutput) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ExampleEnumOutput) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ExampleEnum) *string {
		v := string(e)
		return &v
	}).(codeinfra.StringPtrOutput)
}

type ExampleEnumPtrOutput struct{ *codeinfra.OutputState }

func (ExampleEnumPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ExampleEnum)(nil)).Elem()
}

func (o ExampleEnumPtrOutput) ToExampleEnumPtrOutput() ExampleEnumPtrOutput {
	return o
}

func (o ExampleEnumPtrOutput) ToExampleEnumPtrOutputWithContext(ctx context.Context) ExampleEnumPtrOutput {
	return o
}

func (o ExampleEnumPtrOutput) Elem() ExampleEnumOutput {
	return o.ApplyT(func(v *ExampleEnum) ExampleEnum {
		if v != nil {
			return *v
		}
		var ret ExampleEnum
		return ret
	}).(ExampleEnumOutput)
}

func (o ExampleEnumPtrOutput) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ExampleEnumPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ExampleEnum) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(codeinfra.StringPtrOutput)
}

// ExampleEnumInput is an input type that accepts values of the ExampleEnum enum
// A concrete instance of `ExampleEnumInput` can be one of the following:
//
//	ExampleEnumOne
//	ExampleEnumTwo
type ExampleEnumInput interface {
	codeinfra.Input

	ToExampleEnumOutput() ExampleEnumOutput
	ToExampleEnumOutputWithContext(context.Context) ExampleEnumOutput
}

var exampleEnumPtrType = reflect.TypeOf((**ExampleEnum)(nil)).Elem()

type ExampleEnumPtrInput interface {
	codeinfra.Input

	ToExampleEnumPtrOutput() ExampleEnumPtrOutput
	ToExampleEnumPtrOutputWithContext(context.Context) ExampleEnumPtrOutput
}

type exampleEnumPtr string

func ExampleEnumPtr(v string) ExampleEnumPtrInput {
	return (*exampleEnumPtr)(&v)
}

func (*exampleEnumPtr) ElementType() reflect.Type {
	return exampleEnumPtrType
}

func (in *exampleEnumPtr) ToExampleEnumPtrOutput() ExampleEnumPtrOutput {
	return codeinfra.ToOutput(in).(ExampleEnumPtrOutput)
}

func (in *exampleEnumPtr) ToExampleEnumPtrOutputWithContext(ctx context.Context) ExampleEnumPtrOutput {
	return codeinfra.ToOutputWithContext(ctx, in).(ExampleEnumPtrOutput)
}

type ExampleEnumInputEnum string

const (
	ExampleEnumInputEnumOne = ExampleEnumInputEnum("one")
	ExampleEnumInputEnumTwo = ExampleEnumInputEnum("two")
)

func (ExampleEnumInputEnum) ElementType() reflect.Type {
	return reflect.TypeOf((*ExampleEnumInputEnum)(nil)).Elem()
}

func (e ExampleEnumInputEnum) ToExampleEnumInputEnumOutput() ExampleEnumInputEnumOutput {
	return codeinfra.ToOutput(e).(ExampleEnumInputEnumOutput)
}

func (e ExampleEnumInputEnum) ToExampleEnumInputEnumOutputWithContext(ctx context.Context) ExampleEnumInputEnumOutput {
	return codeinfra.ToOutputWithContext(ctx, e).(ExampleEnumInputEnumOutput)
}

func (e ExampleEnumInputEnum) ToExampleEnumInputEnumPtrOutput() ExampleEnumInputEnumPtrOutput {
	return e.ToExampleEnumInputEnumPtrOutputWithContext(context.Background())
}

func (e ExampleEnumInputEnum) ToExampleEnumInputEnumPtrOutputWithContext(ctx context.Context) ExampleEnumInputEnumPtrOutput {
	return ExampleEnumInputEnum(e).ToExampleEnumInputEnumOutputWithContext(ctx).ToExampleEnumInputEnumPtrOutputWithContext(ctx)
}

func (e ExampleEnumInputEnum) ToStringOutput() codeinfra.StringOutput {
	return codeinfra.ToOutput(codeinfra.String(e)).(codeinfra.StringOutput)
}

func (e ExampleEnumInputEnum) ToStringOutputWithContext(ctx context.Context) codeinfra.StringOutput {
	return codeinfra.ToOutputWithContext(ctx, codeinfra.String(e)).(codeinfra.StringOutput)
}

func (e ExampleEnumInputEnum) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return codeinfra.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ExampleEnumInputEnum) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return codeinfra.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ExampleEnumInputEnumOutput struct{ *codeinfra.OutputState }

func (ExampleEnumInputEnumOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ExampleEnumInputEnum)(nil)).Elem()
}

func (o ExampleEnumInputEnumOutput) ToExampleEnumInputEnumOutput() ExampleEnumInputEnumOutput {
	return o
}

func (o ExampleEnumInputEnumOutput) ToExampleEnumInputEnumOutputWithContext(ctx context.Context) ExampleEnumInputEnumOutput {
	return o
}

func (o ExampleEnumInputEnumOutput) ToExampleEnumInputEnumPtrOutput() ExampleEnumInputEnumPtrOutput {
	return o.ToExampleEnumInputEnumPtrOutputWithContext(context.Background())
}

func (o ExampleEnumInputEnumOutput) ToExampleEnumInputEnumPtrOutputWithContext(ctx context.Context) ExampleEnumInputEnumPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ExampleEnumInputEnum) *ExampleEnumInputEnum {
		return &v
	}).(ExampleEnumInputEnumPtrOutput)
}

func (o ExampleEnumInputEnumOutput) ToStringOutput() codeinfra.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ExampleEnumInputEnumOutput) ToStringOutputWithContext(ctx context.Context) codeinfra.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ExampleEnumInputEnum) string {
		return string(e)
	}).(codeinfra.StringOutput)
}

func (o ExampleEnumInputEnumOutput) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ExampleEnumInputEnumOutput) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ExampleEnumInputEnum) *string {
		v := string(e)
		return &v
	}).(codeinfra.StringPtrOutput)
}

type ExampleEnumInputEnumPtrOutput struct{ *codeinfra.OutputState }

func (ExampleEnumInputEnumPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ExampleEnumInputEnum)(nil)).Elem()
}

func (o ExampleEnumInputEnumPtrOutput) ToExampleEnumInputEnumPtrOutput() ExampleEnumInputEnumPtrOutput {
	return o
}

func (o ExampleEnumInputEnumPtrOutput) ToExampleEnumInputEnumPtrOutputWithContext(ctx context.Context) ExampleEnumInputEnumPtrOutput {
	return o
}

func (o ExampleEnumInputEnumPtrOutput) Elem() ExampleEnumInputEnumOutput {
	return o.ApplyT(func(v *ExampleEnumInputEnum) ExampleEnumInputEnum {
		if v != nil {
			return *v
		}
		var ret ExampleEnumInputEnum
		return ret
	}).(ExampleEnumInputEnumOutput)
}

func (o ExampleEnumInputEnumPtrOutput) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ExampleEnumInputEnumPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ExampleEnumInputEnum) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(codeinfra.StringPtrOutput)
}

// ExampleEnumInputEnumInput is an input type that accepts values of the ExampleEnumInputEnum enum
// A concrete instance of `ExampleEnumInputEnumInput` can be one of the following:
//
//	ExampleEnumInputEnumOne
//	ExampleEnumInputEnumTwo
type ExampleEnumInputEnumInput interface {
	codeinfra.Input

	ToExampleEnumInputEnumOutput() ExampleEnumInputEnumOutput
	ToExampleEnumInputEnumOutputWithContext(context.Context) ExampleEnumInputEnumOutput
}

var exampleEnumInputEnumPtrType = reflect.TypeOf((**ExampleEnumInputEnum)(nil)).Elem()

type ExampleEnumInputEnumPtrInput interface {
	codeinfra.Input

	ToExampleEnumInputEnumPtrOutput() ExampleEnumInputEnumPtrOutput
	ToExampleEnumInputEnumPtrOutputWithContext(context.Context) ExampleEnumInputEnumPtrOutput
}

type exampleEnumInputEnumPtr string

func ExampleEnumInputEnumPtr(v string) ExampleEnumInputEnumPtrInput {
	return (*exampleEnumInputEnumPtr)(&v)
}

func (*exampleEnumInputEnumPtr) ElementType() reflect.Type {
	return exampleEnumInputEnumPtrType
}

func (in *exampleEnumInputEnumPtr) ToExampleEnumInputEnumPtrOutput() ExampleEnumInputEnumPtrOutput {
	return codeinfra.ToOutput(in).(ExampleEnumInputEnumPtrOutput)
}

func (in *exampleEnumInputEnumPtr) ToExampleEnumInputEnumPtrOutputWithContext(ctx context.Context) ExampleEnumInputEnumPtrOutput {
	return codeinfra.ToOutputWithContext(ctx, in).(ExampleEnumInputEnumPtrOutput)
}

type ResourceTypeEnum string

const (
	ResourceTypeEnumHaha     = ResourceTypeEnum("haha")
	ResourceTypeEnumBusiness = ResourceTypeEnum("business")
)

func (ResourceTypeEnum) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceTypeEnum)(nil)).Elem()
}

func (e ResourceTypeEnum) ToResourceTypeEnumOutput() ResourceTypeEnumOutput {
	return codeinfra.ToOutput(e).(ResourceTypeEnumOutput)
}

func (e ResourceTypeEnum) ToResourceTypeEnumOutputWithContext(ctx context.Context) ResourceTypeEnumOutput {
	return codeinfra.ToOutputWithContext(ctx, e).(ResourceTypeEnumOutput)
}

func (e ResourceTypeEnum) ToResourceTypeEnumPtrOutput() ResourceTypeEnumPtrOutput {
	return e.ToResourceTypeEnumPtrOutputWithContext(context.Background())
}

func (e ResourceTypeEnum) ToResourceTypeEnumPtrOutputWithContext(ctx context.Context) ResourceTypeEnumPtrOutput {
	return ResourceTypeEnum(e).ToResourceTypeEnumOutputWithContext(ctx).ToResourceTypeEnumPtrOutputWithContext(ctx)
}

func (e ResourceTypeEnum) ToStringOutput() codeinfra.StringOutput {
	return codeinfra.ToOutput(codeinfra.String(e)).(codeinfra.StringOutput)
}

func (e ResourceTypeEnum) ToStringOutputWithContext(ctx context.Context) codeinfra.StringOutput {
	return codeinfra.ToOutputWithContext(ctx, codeinfra.String(e)).(codeinfra.StringOutput)
}

func (e ResourceTypeEnum) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return codeinfra.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ResourceTypeEnum) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return codeinfra.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ResourceTypeEnumOutput struct{ *codeinfra.OutputState }

func (ResourceTypeEnumOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceTypeEnum)(nil)).Elem()
}

func (o ResourceTypeEnumOutput) ToResourceTypeEnumOutput() ResourceTypeEnumOutput {
	return o
}

func (o ResourceTypeEnumOutput) ToResourceTypeEnumOutputWithContext(ctx context.Context) ResourceTypeEnumOutput {
	return o
}

func (o ResourceTypeEnumOutput) ToResourceTypeEnumPtrOutput() ResourceTypeEnumPtrOutput {
	return o.ToResourceTypeEnumPtrOutputWithContext(context.Background())
}

func (o ResourceTypeEnumOutput) ToResourceTypeEnumPtrOutputWithContext(ctx context.Context) ResourceTypeEnumPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ResourceTypeEnum) *ResourceTypeEnum {
		return &v
	}).(ResourceTypeEnumPtrOutput)
}

func (o ResourceTypeEnumOutput) ToStringOutput() codeinfra.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ResourceTypeEnumOutput) ToStringOutputWithContext(ctx context.Context) codeinfra.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ResourceTypeEnum) string {
		return string(e)
	}).(codeinfra.StringOutput)
}

func (o ResourceTypeEnumOutput) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ResourceTypeEnumOutput) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ResourceTypeEnum) *string {
		v := string(e)
		return &v
	}).(codeinfra.StringPtrOutput)
}

type ResourceTypeEnumPtrOutput struct{ *codeinfra.OutputState }

func (ResourceTypeEnumPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceTypeEnum)(nil)).Elem()
}

func (o ResourceTypeEnumPtrOutput) ToResourceTypeEnumPtrOutput() ResourceTypeEnumPtrOutput {
	return o
}

func (o ResourceTypeEnumPtrOutput) ToResourceTypeEnumPtrOutputWithContext(ctx context.Context) ResourceTypeEnumPtrOutput {
	return o
}

func (o ResourceTypeEnumPtrOutput) Elem() ResourceTypeEnumOutput {
	return o.ApplyT(func(v *ResourceTypeEnum) ResourceTypeEnum {
		if v != nil {
			return *v
		}
		var ret ResourceTypeEnum
		return ret
	}).(ResourceTypeEnumOutput)
}

func (o ResourceTypeEnumPtrOutput) ToStringPtrOutput() codeinfra.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ResourceTypeEnumPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) codeinfra.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ResourceTypeEnum) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(codeinfra.StringPtrOutput)
}

// ResourceTypeEnumInput is an input type that accepts values of the ResourceTypeEnum enum
// A concrete instance of `ResourceTypeEnumInput` can be one of the following:
//
//	ResourceTypeEnumHaha
//	ResourceTypeEnumBusiness
type ResourceTypeEnumInput interface {
	codeinfra.Input

	ToResourceTypeEnumOutput() ResourceTypeEnumOutput
	ToResourceTypeEnumOutputWithContext(context.Context) ResourceTypeEnumOutput
}

var resourceTypeEnumPtrType = reflect.TypeOf((**ResourceTypeEnum)(nil)).Elem()

type ResourceTypeEnumPtrInput interface {
	codeinfra.Input

	ToResourceTypeEnumPtrOutput() ResourceTypeEnumPtrOutput
	ToResourceTypeEnumPtrOutputWithContext(context.Context) ResourceTypeEnumPtrOutput
}

type resourceTypeEnumPtr string

func ResourceTypeEnumPtr(v string) ResourceTypeEnumPtrInput {
	return (*resourceTypeEnumPtr)(&v)
}

func (*resourceTypeEnumPtr) ElementType() reflect.Type {
	return resourceTypeEnumPtrType
}

func (in *resourceTypeEnumPtr) ToResourceTypeEnumPtrOutput() ResourceTypeEnumPtrOutput {
	return codeinfra.ToOutput(in).(ResourceTypeEnumPtrOutput)
}

func (in *resourceTypeEnumPtr) ToResourceTypeEnumPtrOutputWithContext(ctx context.Context) ResourceTypeEnumPtrOutput {
	return codeinfra.ToOutputWithContext(ctx, in).(ResourceTypeEnumPtrOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*ExampleEnumInput)(nil)).Elem(), ExampleEnum("one"))
	codeinfra.RegisterInputType(reflect.TypeOf((*ExampleEnumPtrInput)(nil)).Elem(), ExampleEnum("one"))
	codeinfra.RegisterInputType(reflect.TypeOf((*ExampleEnumInputEnumInput)(nil)).Elem(), ExampleEnumInputEnum("one"))
	codeinfra.RegisterInputType(reflect.TypeOf((*ExampleEnumInputEnumPtrInput)(nil)).Elem(), ExampleEnumInputEnum("one"))
	codeinfra.RegisterInputType(reflect.TypeOf((*ResourceTypeEnumInput)(nil)).Elem(), ResourceTypeEnum("haha"))
	codeinfra.RegisterInputType(reflect.TypeOf((*ResourceTypeEnumPtrInput)(nil)).Elem(), ResourceTypeEnum("haha"))
	codeinfra.RegisterOutputType(ExampleEnumOutput{})
	codeinfra.RegisterOutputType(ExampleEnumPtrOutput{})
	codeinfra.RegisterOutputType(ExampleEnumInputEnumOutput{})
	codeinfra.RegisterOutputType(ExampleEnumInputEnumPtrOutput{})
	codeinfra.RegisterOutputType(ResourceTypeEnumOutput{})
	codeinfra.RegisterOutputType(ResourceTypeEnumPtrOutput{})
}
