// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"naming-collisions/example/internal"
)

var _ = internal.GetEnvOrDefault

type Object struct {
	Bar *string `codeinfra:"bar"`
}

// ObjectInput is an input type that accepts ObjectArgs and ObjectOutput values.
// You can construct a concrete instance of `ObjectInput` via:
//
//	ObjectArgs{...}
type ObjectInput interface {
	codeinfra.Input

	ToObjectOutput() ObjectOutput
	ToObjectOutputWithContext(context.Context) ObjectOutput
}

type ObjectArgs struct {
	Bar codeinfra.StringPtrInput `codeinfra:"bar"`
}

func (ObjectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Object)(nil)).Elem()
}

func (i ObjectArgs) ToObjectOutput() ObjectOutput {
	return i.ToObjectOutputWithContext(context.Background())
}

func (i ObjectArgs) ToObjectOutputWithContext(ctx context.Context) ObjectOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(ObjectOutput)
}

type ObjectOutput struct{ *codeinfra.OutputState }

func (ObjectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Object)(nil)).Elem()
}

func (o ObjectOutput) ToObjectOutput() ObjectOutput {
	return o
}

func (o ObjectOutput) ToObjectOutputWithContext(ctx context.Context) ObjectOutput {
	return o
}

func (o ObjectOutput) Bar() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v Object) *string { return v.Bar }).(codeinfra.StringPtrOutput)
}

type ObjectInputType struct {
	Bar *string `codeinfra:"bar"`
}

// ObjectInputTypeInput is an input type that accepts ObjectInputTypeArgs and ObjectInputTypeOutput values.
// You can construct a concrete instance of `ObjectInputTypeInput` via:
//
//	ObjectInputTypeArgs{...}
type ObjectInputTypeInput interface {
	codeinfra.Input

	ToObjectInputTypeOutput() ObjectInputTypeOutput
	ToObjectInputTypeOutputWithContext(context.Context) ObjectInputTypeOutput
}

type ObjectInputTypeArgs struct {
	Bar codeinfra.StringPtrInput `codeinfra:"bar"`
}

func (ObjectInputTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectInputType)(nil)).Elem()
}

func (i ObjectInputTypeArgs) ToObjectInputTypeOutput() ObjectInputTypeOutput {
	return i.ToObjectInputTypeOutputWithContext(context.Background())
}

func (i ObjectInputTypeArgs) ToObjectInputTypeOutputWithContext(ctx context.Context) ObjectInputTypeOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(ObjectInputTypeOutput)
}

type ObjectInputTypeOutput struct{ *codeinfra.OutputState }

func (ObjectInputTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectInputType)(nil)).Elem()
}

func (o ObjectInputTypeOutput) ToObjectInputTypeOutput() ObjectInputTypeOutput {
	return o
}

func (o ObjectInputTypeOutput) ToObjectInputTypeOutputWithContext(ctx context.Context) ObjectInputTypeOutput {
	return o
}

func (o ObjectInputTypeOutput) Bar() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v ObjectInputType) *string { return v.Bar }).(codeinfra.StringPtrOutput)
}

type ResourceType struct {
	Name *string `codeinfra:"name"`
}

// ResourceTypeInput is an input type that accepts ResourceTypeArgs and ResourceTypeOutput values.
// You can construct a concrete instance of `ResourceTypeInput` via:
//
//	ResourceTypeArgs{...}
type ResourceTypeInput interface {
	codeinfra.Input

	ToResourceTypeOutput() ResourceTypeOutput
	ToResourceTypeOutputWithContext(context.Context) ResourceTypeOutput
}

type ResourceTypeArgs struct {
	Name codeinfra.StringPtrInput `codeinfra:"name"`
}

func (ResourceTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceType)(nil)).Elem()
}

func (i ResourceTypeArgs) ToResourceTypeOutput() ResourceTypeOutput {
	return i.ToResourceTypeOutputWithContext(context.Background())
}

func (i ResourceTypeArgs) ToResourceTypeOutputWithContext(ctx context.Context) ResourceTypeOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(ResourceTypeOutput)
}

type ResourceTypeOutput struct{ *codeinfra.OutputState }

func (ResourceTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceType)(nil)).Elem()
}

func (o ResourceTypeOutput) ToResourceTypeOutput() ResourceTypeOutput {
	return o
}

func (o ResourceTypeOutput) ToResourceTypeOutputWithContext(ctx context.Context) ResourceTypeOutput {
	return o
}

func (o ResourceTypeOutput) Name() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v ResourceType) *string { return v.Name }).(codeinfra.StringPtrOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*ObjectInput)(nil)).Elem(), ObjectArgs{})
	codeinfra.RegisterInputType(reflect.TypeOf((*ObjectInputTypeInput)(nil)).Elem(), ObjectInputTypeArgs{})
	codeinfra.RegisterInputType(reflect.TypeOf((*ResourceTypeInput)(nil)).Elem(), ResourceTypeArgs{})
	codeinfra.RegisterOutputType(ObjectOutput{})
	codeinfra.RegisterOutputType(ObjectInputTypeOutput{})
	codeinfra.RegisterOutputType(ResourceTypeOutput{})
}
