// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"example.com/codeinfra-configstation/sdk/go/configstation/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

var _ = internal.GetEnvOrDefault

type Sandwich struct {
	Bread   *string  `codeinfra:"bread"`
	Veggies []string `codeinfra:"veggies"`
}

// SandwichInput is an input type that accepts SandwichArgs and SandwichOutput values.
// You can construct a concrete instance of `SandwichInput` via:
//
//	SandwichArgs{...}
type SandwichInput interface {
	codeinfra.Input

	ToSandwichOutput() SandwichOutput
	ToSandwichOutputWithContext(context.Context) SandwichOutput
}

type SandwichArgs struct {
	Bread   codeinfra.StringPtrInput   `codeinfra:"bread"`
	Veggies codeinfra.StringArrayInput `codeinfra:"veggies"`
}

func (SandwichArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Sandwich)(nil)).Elem()
}

func (i SandwichArgs) ToSandwichOutput() SandwichOutput {
	return i.ToSandwichOutputWithContext(context.Background())
}

func (i SandwichArgs) ToSandwichOutputWithContext(ctx context.Context) SandwichOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(SandwichOutput)
}

// SandwichArrayInput is an input type that accepts SandwichArray and SandwichArrayOutput values.
// You can construct a concrete instance of `SandwichArrayInput` via:
//
//	SandwichArray{ SandwichArgs{...} }
type SandwichArrayInput interface {
	codeinfra.Input

	ToSandwichArrayOutput() SandwichArrayOutput
	ToSandwichArrayOutputWithContext(context.Context) SandwichArrayOutput
}

type SandwichArray []SandwichInput

func (SandwichArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Sandwich)(nil)).Elem()
}

func (i SandwichArray) ToSandwichArrayOutput() SandwichArrayOutput {
	return i.ToSandwichArrayOutputWithContext(context.Background())
}

func (i SandwichArray) ToSandwichArrayOutputWithContext(ctx context.Context) SandwichArrayOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(SandwichArrayOutput)
}

type SandwichOutput struct{ *codeinfra.OutputState }

func (SandwichOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Sandwich)(nil)).Elem()
}

func (o SandwichOutput) ToSandwichOutput() SandwichOutput {
	return o
}

func (o SandwichOutput) ToSandwichOutputWithContext(ctx context.Context) SandwichOutput {
	return o
}

func (o SandwichOutput) Bread() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v Sandwich) *string { return v.Bread }).(codeinfra.StringPtrOutput)
}

func (o SandwichOutput) Veggies() codeinfra.StringArrayOutput {
	return o.ApplyT(func(v Sandwich) []string { return v.Veggies }).(codeinfra.StringArrayOutput)
}

type SandwichArrayOutput struct{ *codeinfra.OutputState }

func (SandwichArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Sandwich)(nil)).Elem()
}

func (o SandwichArrayOutput) ToSandwichArrayOutput() SandwichArrayOutput {
	return o
}

func (o SandwichArrayOutput) ToSandwichArrayOutputWithContext(ctx context.Context) SandwichArrayOutput {
	return o
}

func (o SandwichArrayOutput) Index(i codeinfra.IntInput) SandwichOutput {
	return codeinfra.All(o, i).ApplyT(func(vs []interface{}) Sandwich {
		return vs[0].([]Sandwich)[vs[1].(int)]
	}).(SandwichOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*SandwichInput)(nil)).Elem(), SandwichArgs{})
	codeinfra.RegisterInputType(reflect.TypeOf((*SandwichArrayInput)(nil)).Elem(), SandwichArray{})
	codeinfra.RegisterOutputType(SandwichOutput{})
	codeinfra.RegisterOutputType(SandwichArrayOutput{})
}
