// *** WARNING: this file was generated by codeinfra-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface Data {
    private: string;
    public: string;
}

