// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"replace-on-change/example/internal"
)

type NoRecursive struct {
	codeinfra.CustomResourceState

	Rec       RecPtrOutput           `codeinfra:"rec"`
	ReplaceMe codeinfra.StringPtrOutput `codeinfra:"replaceMe"`
}

// NewNoRecursive registers a new resource with the given unique name, arguments, and options.
func NewNoRecursive(ctx *codeinfra.Context,
	name string, args *NoRecursiveArgs, opts ...codeinfra.ResourceOption) (*NoRecursive, error) {
	if args == nil {
		args = &NoRecursiveArgs{}
	}

	replaceOnChanges := codeinfra.ReplaceOnChanges([]string{
		"replaceMe",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NoRecursive
	err := ctx.RegisterResource("example::NoRecursive", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNoRecursive gets an existing NoRecursive resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNoRecursive(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *NoRecursiveState, opts ...codeinfra.ResourceOption) (*NoRecursive, error) {
	var resource NoRecursive
	err := ctx.ReadResource("example::NoRecursive", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NoRecursive resources.
type noRecursiveState struct {
}

type NoRecursiveState struct {
}

func (NoRecursiveState) ElementType() reflect.Type {
	return reflect.TypeOf((*noRecursiveState)(nil)).Elem()
}

type noRecursiveArgs struct {
}

// The set of arguments for constructing a NoRecursive resource.
type NoRecursiveArgs struct {
}

func (NoRecursiveArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*noRecursiveArgs)(nil)).Elem()
}

type NoRecursiveInput interface {
	codeinfra.Input

	ToNoRecursiveOutput() NoRecursiveOutput
	ToNoRecursiveOutputWithContext(ctx context.Context) NoRecursiveOutput
}

func (*NoRecursive) ElementType() reflect.Type {
	return reflect.TypeOf((**NoRecursive)(nil)).Elem()
}

func (i *NoRecursive) ToNoRecursiveOutput() NoRecursiveOutput {
	return i.ToNoRecursiveOutputWithContext(context.Background())
}

func (i *NoRecursive) ToNoRecursiveOutputWithContext(ctx context.Context) NoRecursiveOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(NoRecursiveOutput)
}

// NoRecursiveArrayInput is an input type that accepts NoRecursiveArray and NoRecursiveArrayOutput values.
// You can construct a concrete instance of `NoRecursiveArrayInput` via:
//
//	NoRecursiveArray{ NoRecursiveArgs{...} }
type NoRecursiveArrayInput interface {
	codeinfra.Input

	ToNoRecursiveArrayOutput() NoRecursiveArrayOutput
	ToNoRecursiveArrayOutputWithContext(context.Context) NoRecursiveArrayOutput
}

type NoRecursiveArray []NoRecursiveInput

func (NoRecursiveArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NoRecursive)(nil)).Elem()
}

func (i NoRecursiveArray) ToNoRecursiveArrayOutput() NoRecursiveArrayOutput {
	return i.ToNoRecursiveArrayOutputWithContext(context.Background())
}

func (i NoRecursiveArray) ToNoRecursiveArrayOutputWithContext(ctx context.Context) NoRecursiveArrayOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(NoRecursiveArrayOutput)
}

// NoRecursiveMapInput is an input type that accepts NoRecursiveMap and NoRecursiveMapOutput values.
// You can construct a concrete instance of `NoRecursiveMapInput` via:
//
//	NoRecursiveMap{ "key": NoRecursiveArgs{...} }
type NoRecursiveMapInput interface {
	codeinfra.Input

	ToNoRecursiveMapOutput() NoRecursiveMapOutput
	ToNoRecursiveMapOutputWithContext(context.Context) NoRecursiveMapOutput
}

type NoRecursiveMap map[string]NoRecursiveInput

func (NoRecursiveMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NoRecursive)(nil)).Elem()
}

func (i NoRecursiveMap) ToNoRecursiveMapOutput() NoRecursiveMapOutput {
	return i.ToNoRecursiveMapOutputWithContext(context.Background())
}

func (i NoRecursiveMap) ToNoRecursiveMapOutputWithContext(ctx context.Context) NoRecursiveMapOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(NoRecursiveMapOutput)
}

type NoRecursiveOutput struct{ *codeinfra.OutputState }

func (NoRecursiveOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NoRecursive)(nil)).Elem()
}

func (o NoRecursiveOutput) ToNoRecursiveOutput() NoRecursiveOutput {
	return o
}

func (o NoRecursiveOutput) ToNoRecursiveOutputWithContext(ctx context.Context) NoRecursiveOutput {
	return o
}

func (o NoRecursiveOutput) Rec() RecPtrOutput {
	return o.ApplyT(func(v *NoRecursive) RecPtrOutput { return v.Rec }).(RecPtrOutput)
}

func (o NoRecursiveOutput) ReplaceMe() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v *NoRecursive) codeinfra.StringPtrOutput { return v.ReplaceMe }).(codeinfra.StringPtrOutput)
}

type NoRecursiveArrayOutput struct{ *codeinfra.OutputState }

func (NoRecursiveArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NoRecursive)(nil)).Elem()
}

func (o NoRecursiveArrayOutput) ToNoRecursiveArrayOutput() NoRecursiveArrayOutput {
	return o
}

func (o NoRecursiveArrayOutput) ToNoRecursiveArrayOutputWithContext(ctx context.Context) NoRecursiveArrayOutput {
	return o
}

func (o NoRecursiveArrayOutput) Index(i codeinfra.IntInput) NoRecursiveOutput {
	return codeinfra.All(o, i).ApplyT(func(vs []interface{}) *NoRecursive {
		return vs[0].([]*NoRecursive)[vs[1].(int)]
	}).(NoRecursiveOutput)
}

type NoRecursiveMapOutput struct{ *codeinfra.OutputState }

func (NoRecursiveMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NoRecursive)(nil)).Elem()
}

func (o NoRecursiveMapOutput) ToNoRecursiveMapOutput() NoRecursiveMapOutput {
	return o
}

func (o NoRecursiveMapOutput) ToNoRecursiveMapOutputWithContext(ctx context.Context) NoRecursiveMapOutput {
	return o
}

func (o NoRecursiveMapOutput) MapIndex(k codeinfra.StringInput) NoRecursiveOutput {
	return codeinfra.All(o, k).ApplyT(func(vs []interface{}) *NoRecursive {
		return vs[0].(map[string]*NoRecursive)[vs[1].(string)]
	}).(NoRecursiveOutput)
}

func init() {
	codeinfra.RegisterOutputType(NoRecursiveOutput{})
	codeinfra.RegisterOutputType(NoRecursiveArrayOutput{})
	codeinfra.RegisterOutputType(NoRecursiveMapOutput{})
}
