// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"output-funcs-tfbridge20/mypkg/internal"
)

// Taken from codeinfra-AWS to regress an issue
//
// Deprecated: aws.getAmiIds has been deprecated in favor of aws.ec2.getAmiIds
func GetAmiIds(ctx *codeinfra.Context, args *GetAmiIdsArgs, opts ...codeinfra.InvokeOption) (*GetAmiIdsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAmiIdsResult
	err := ctx.Invoke("mypkg::getAmiIds", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAmiIds.
type GetAmiIdsArgs struct {
	// Limit search to users with *explicit* launch
	// permission on  the image. Valid items are the numeric account ID or `self`.
	ExecutableUsers []string `codeinfra:"executableUsers"`
	// One or more name/value pairs to filter off of. There
	// are several valid keys, for a full reference, check out
	// [describe-images in the AWS CLI reference][1].
	Filters []GetAmiIdsFilter `codeinfra:"filters"`
	// A regex string to apply to the AMI list returned
	// by AWS. This allows more advanced filtering not supported from the AWS API.
	// This filtering is done locally on what AWS returns, and could have a performance
	// impact if the result is large. It is recommended to combine this with other
	// options to narrow down the list AWS returns.
	NameRegex *string `codeinfra:"nameRegex"`
	// List of AMI owners to limit search. At least 1 value must be specified. Valid values: an AWS account ID, `self` (the current account), or an AWS owner alias (e.g. `amazon`, `aws-marketplace`, `microsoft`).
	Owners []string `codeinfra:"owners"`
	// Used to sort AMIs by creation time.
	SortAscending *bool `codeinfra:"sortAscending"`
}

// A collection of values returned by getAmiIds.
type GetAmiIdsResult struct {
	ExecutableUsers []string          `codeinfra:"executableUsers"`
	Filters         []GetAmiIdsFilter `codeinfra:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id            string   `codeinfra:"id"`
	Ids           []string `codeinfra:"ids"`
	NameRegex     *string  `codeinfra:"nameRegex"`
	Owners        []string `codeinfra:"owners"`
	SortAscending *bool    `codeinfra:"sortAscending"`
}

func GetAmiIdsOutput(ctx *codeinfra.Context, args GetAmiIdsOutputArgs, opts ...codeinfra.InvokeOption) GetAmiIdsResultOutput {
	return codeinfra.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAmiIdsResultOutput, error) {
			args := v.(GetAmiIdsArgs)
			options := codeinfra.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mypkg::getAmiIds", args, GetAmiIdsResultOutput{}, options).(GetAmiIdsResultOutput), nil
		}).(GetAmiIdsResultOutput)
}

// A collection of arguments for invoking getAmiIds.
type GetAmiIdsOutputArgs struct {
	// Limit search to users with *explicit* launch
	// permission on  the image. Valid items are the numeric account ID or `self`.
	ExecutableUsers codeinfra.StringArrayInput `codeinfra:"executableUsers"`
	// One or more name/value pairs to filter off of. There
	// are several valid keys, for a full reference, check out
	// [describe-images in the AWS CLI reference][1].
	Filters GetAmiIdsFilterArrayInput `codeinfra:"filters"`
	// A regex string to apply to the AMI list returned
	// by AWS. This allows more advanced filtering not supported from the AWS API.
	// This filtering is done locally on what AWS returns, and could have a performance
	// impact if the result is large. It is recommended to combine this with other
	// options to narrow down the list AWS returns.
	NameRegex codeinfra.StringPtrInput `codeinfra:"nameRegex"`
	// List of AMI owners to limit search. At least 1 value must be specified. Valid values: an AWS account ID, `self` (the current account), or an AWS owner alias (e.g. `amazon`, `aws-marketplace`, `microsoft`).
	Owners codeinfra.StringArrayInput `codeinfra:"owners"`
	// Used to sort AMIs by creation time.
	SortAscending codeinfra.BoolPtrInput `codeinfra:"sortAscending"`
}

func (GetAmiIdsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAmiIdsArgs)(nil)).Elem()
}

// A collection of values returned by getAmiIds.
type GetAmiIdsResultOutput struct{ *codeinfra.OutputState }

func (GetAmiIdsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAmiIdsResult)(nil)).Elem()
}

func (o GetAmiIdsResultOutput) ToGetAmiIdsResultOutput() GetAmiIdsResultOutput {
	return o
}

func (o GetAmiIdsResultOutput) ToGetAmiIdsResultOutputWithContext(ctx context.Context) GetAmiIdsResultOutput {
	return o
}

func (o GetAmiIdsResultOutput) ExecutableUsers() codeinfra.StringArrayOutput {
	return o.ApplyT(func(v GetAmiIdsResult) []string { return v.ExecutableUsers }).(codeinfra.StringArrayOutput)
}

func (o GetAmiIdsResultOutput) Filters() GetAmiIdsFilterArrayOutput {
	return o.ApplyT(func(v GetAmiIdsResult) []GetAmiIdsFilter { return v.Filters }).(GetAmiIdsFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAmiIdsResultOutput) Id() codeinfra.StringOutput {
	return o.ApplyT(func(v GetAmiIdsResult) string { return v.Id }).(codeinfra.StringOutput)
}

func (o GetAmiIdsResultOutput) Ids() codeinfra.StringArrayOutput {
	return o.ApplyT(func(v GetAmiIdsResult) []string { return v.Ids }).(codeinfra.StringArrayOutput)
}

func (o GetAmiIdsResultOutput) NameRegex() codeinfra.StringPtrOutput {
	return o.ApplyT(func(v GetAmiIdsResult) *string { return v.NameRegex }).(codeinfra.StringPtrOutput)
}

func (o GetAmiIdsResultOutput) Owners() codeinfra.StringArrayOutput {
	return o.ApplyT(func(v GetAmiIdsResult) []string { return v.Owners }).(codeinfra.StringArrayOutput)
}

func (o GetAmiIdsResultOutput) SortAscending() codeinfra.BoolPtrOutput {
	return o.ApplyT(func(v GetAmiIdsResult) *bool { return v.SortAscending }).(codeinfra.BoolPtrOutput)
}

func init() {
	codeinfra.RegisterOutputType(GetAmiIdsResultOutput{})
}
