// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * The list of configurations.
 * API Version: 2020-12-01-preview.
 */
export function listConfigurations(args: ListConfigurationsArgs, opts?: codeinfra.InvokeOptions): Promise<ListConfigurationsResult> {
    opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return codeinfra.runtime.invoke("myedgeorder::listConfigurations", {
        "configurationFilters": args.configurationFilters,
        "customerSubscriptionDetails": args.customerSubscriptionDetails,
        "skipToken": args.skipToken,
    }, opts);
}

export interface ListConfigurationsArgs {
    /**
     * Holds details about product hierarchy information and filterable property.
     */
    configurationFilters: inputs.ConfigurationFilters[];
    /**
     * Customer subscription properties. Clients can display available products to unregistered customers by explicitly passing subscription details
     */
    customerSubscriptionDetails?: inputs.CustomerSubscriptionDetails;
    /**
     * $skipToken is supported on list of configurations, which provides the next page in the list of configurations.
     */
    skipToken?: string;
}

/**
 * The list of configurations.
 */
export interface ListConfigurationsResult {
    /**
     * Link for the next set of configurations.
     */
    readonly nextLink?: string;
    /**
     * List of configurations.
     */
    readonly value: outputs.ConfigurationResponse[];
}
/**
 * The list of configurations.
 * API Version: 2020-12-01-preview.
 */
export function listConfigurationsOutput(args: ListConfigurationsOutputArgs, opts?: codeinfra.InvokeOutputOptions): codeinfra.Output<ListConfigurationsResult> {
    opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return codeinfra.runtime.invokeOutput("myedgeorder::listConfigurations", {
        "configurationFilters": args.configurationFilters,
        "customerSubscriptionDetails": args.customerSubscriptionDetails,
        "skipToken": args.skipToken,
    }, opts);
}

export interface ListConfigurationsOutputArgs {
    /**
     * Holds details about product hierarchy information and filterable property.
     */
    configurationFilters: codeinfra.Input<codeinfra.Input<inputs.ConfigurationFiltersArgs>[]>;
    /**
     * Customer subscription properties. Clients can display available products to unregistered customers by explicitly passing subscription details
     */
    customerSubscriptionDetails?: codeinfra.Input<inputs.CustomerSubscriptionDetailsArgs>;
    /**
     * $skipToken is supported on list of configurations, which provides the next page in the list of configurations.
     */
    skipToken?: codeinfra.Input<string>;
}
