# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'Baz',
    'BazDict',
]

MYPY = False

if not MYPY:
    class BazDict(TypedDict):
        hello: NotRequired[str]
        world: NotRequired[str]
elif False:
    BazDict: TypeAlias = Mapping[str, Any]

@codeinfra.input_type
class Baz:
    def __init__(__self__, *,
                 hello: Optional[str] = None,
                 world: Optional[str] = None):
        if hello is not None:
            codeinfra.set(__self__, "hello", hello)
        if world is not None:
            codeinfra.set(__self__, "world", world)

    @property
    @codeinfra.getter
    def hello(self) -> Optional[str]:
        return codeinfra.get(self, "hello")

    @hello.setter
    def hello(self, value: Optional[str]):
        codeinfra.set(self, "hello", value)

    @property
    @codeinfra.getter
    def world(self) -> Optional[str]:
        return codeinfra.get(self, "world")

    @world.setter
    def world(self, value: Optional[str]):
        codeinfra.set(self, "world", value)


