# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *
from ._inputs import *

__all__ = ['ProviderArgs', 'Provider']

@codeinfra.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 hash: codeinfra.Input['HashKind'],
                 shared: codeinfra.Input['SharedArgs'],
                 user: codeinfra.Input[str],
                 password: Optional[codeinfra.Input[str]] = None):
        """
        The set of arguments for constructing a Provider resource.
        :param codeinfra.Input['HashKind'] hash: The (entirely uncryptographic) hash function used to encode the "password".
        :param codeinfra.Input[str] user: The username. Its important but not secret.
        :param codeinfra.Input[str] password: The password. It is very secret.
        """
        codeinfra.set(__self__, "hash", hash)
        codeinfra.set(__self__, "shared", shared)
        codeinfra.set(__self__, "user", user)
        if password is None:
            password = (_utilities.get_env('FOO') or '')
        if password is not None:
            codeinfra.set(__self__, "password", password)

    @property
    @codeinfra.getter
    def hash(self) -> codeinfra.Input['HashKind']:
        """
        The (entirely uncryptographic) hash function used to encode the "password".
        """
        return codeinfra.get(self, "hash")

    @hash.setter
    def hash(self, value: codeinfra.Input['HashKind']):
        codeinfra.set(self, "hash", value)

    @property
    @codeinfra.getter
    def shared(self) -> codeinfra.Input['SharedArgs']:
        return codeinfra.get(self, "shared")

    @shared.setter
    def shared(self, value: codeinfra.Input['SharedArgs']):
        codeinfra.set(self, "shared", value)

    @property
    @codeinfra.getter
    def user(self) -> codeinfra.Input[str]:
        """
        The username. Its important but not secret.
        """
        return codeinfra.get(self, "user")

    @user.setter
    def user(self, value: codeinfra.Input[str]):
        codeinfra.set(self, "user", value)

    @property
    @codeinfra.getter
    def password(self) -> Optional[codeinfra.Input[str]]:
        """
        The password. It is very secret.
        """
        return codeinfra.get(self, "password")

    @password.setter
    def password(self, value: Optional[codeinfra.Input[str]]):
        codeinfra.set(self, "password", value)


class Provider(codeinfra.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 hash: Optional[codeinfra.Input['HashKind']] = None,
                 password: Optional[codeinfra.Input[str]] = None,
                 shared: Optional[codeinfra.Input[codeinfra.InputType['SharedArgs']]] = None,
                 user: Optional[codeinfra.Input[str]] = None,
                 __props__=None):
        """
        Create a Credentials resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        :param codeinfra.Input['HashKind'] hash: The (entirely uncryptographic) hash function used to encode the "password".
        :param codeinfra.Input[str] password: The password. It is very secret.
        :param codeinfra.Input[str] user: The username. Its important but not secret.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProviderArgs,
                 opts: Optional[codeinfra.ResourceOptions] = None):
        """
        Create a Credentials resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param codeinfra.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, codeinfra.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[codeinfra.ResourceOptions] = None,
                 hash: Optional[codeinfra.Input['HashKind']] = None,
                 password: Optional[codeinfra.Input[str]] = None,
                 shared: Optional[codeinfra.Input[codeinfra.InputType['SharedArgs']]] = None,
                 user: Optional[codeinfra.Input[str]] = None,
                 __props__=None):
        opts = codeinfra.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, codeinfra.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if hash is None and not opts.urn:
                raise TypeError("Missing required property 'hash'")
            __props__.__dict__["hash"] = codeinfra.Output.from_input(hash).apply(codeinfra.runtime.to_json) if hash is not None else None
            if password is None:
                password = (_utilities.get_env('FOO') or '')
            __props__.__dict__["password"] = None if password is None else codeinfra.Output.secret(password)
            if shared is None and not opts.urn:
                raise TypeError("Missing required property 'shared'")
            __props__.__dict__["shared"] = codeinfra.Output.from_input(shared).apply(codeinfra.runtime.to_json) if shared is not None else None
            if user is None and not opts.urn:
                raise TypeError("Missing required property 'user'")
            __props__.__dict__["user"] = user
        secret_opts = codeinfra.ResourceOptions(additional_secret_outputs=["password"])
        opts = codeinfra.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'credentials',
            resource_name,
            __props__,
            opts)

    @property
    @codeinfra.getter
    def password(self) -> codeinfra.Output[Optional[str]]:
        """
        The password. It is very secret.
        """
        return codeinfra.get(self, "password")

    @property
    @codeinfra.getter
    def user(self) -> codeinfra.Output[str]:
        """
        The username. Its important but not secret.
        """
        return codeinfra.get(self, "user")

