// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import {Resource} from "..";

export interface ConfigMapArgs {
    config?: codeinfra.Input<string>;
}

export interface ObjectArgs {
    bar?: codeinfra.Input<string>;
    configs?: codeinfra.Input<codeinfra.Input<inputs.ConfigMapArgs>[]>;
    foo?: codeinfra.Input<Resource>;
    /**
     * List of lists of other objects
     */
    others?: codeinfra.Input<codeinfra.Input<codeinfra.Input<inputs.SomeOtherObjectArgs>[]>[]>;
    /**
     * Mapping from string to list of some other object
     */
    stillOthers?: codeinfra.Input<{[key: string]: codeinfra.Input<codeinfra.Input<inputs.SomeOtherObjectArgs>[]>}>;
}

export interface ObjectWithNodeOptionalInputsArgs {
    bar?: codeinfra.Input<number>;
    foo?: codeinfra.Input<string>;
}

export interface SomeOtherObjectArgs {
    baz?: codeinfra.Input<string>;
}
