// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface TypeWithAssetsArgs {
    archive?: codeinfra.Input<codeinfra.asset.Archive>;
    asset: codeinfra.Input<codeinfra.asset.Asset | codeinfra.asset.Archive>;
    plainArchive: codeinfra.asset.Archive;
    plainAsset?: codeinfra.asset.Asset | codeinfra.asset.Archive;
}
