# coding=utf-8
# *** WARNING: this file was generated by codeinfra-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'MyInvokeResult',
    'AwaitableMyInvokeResult',
    'my_invoke',
    'my_invoke_output',
]

@codeinfra.output_type
class MyInvokeResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, str):
            raise TypeError("Expected argument 'result' to be a str")
        codeinfra.set(__self__, "result", result)

    @property
    @codeinfra.getter
    def result(self) -> str:
        return codeinfra.get(self, "result")


class AwaitableMyInvokeResult(MyInvokeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return MyInvokeResult(
            result=self.result)


def my_invoke(value: Optional[str] = None,
              opts: Optional[codeinfra.InvokeOptions] = None) -> AwaitableMyInvokeResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['value'] = value
    opts = codeinfra.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = codeinfra.runtime.invoke('simple-invoke:index:myInvoke', __args__, opts=opts, typ=MyInvokeResult).value

    return AwaitableMyInvokeResult(
        result=codeinfra.get(__ret__, 'result'))
def my_invoke_output(value: Optional[codeinfra.Input[str]] = None,
                     opts: Optional[Union[codeinfra.InvokeOptions, codeinfra.InvokeOutputOptions]] = None) -> codeinfra.Output[MyInvokeResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['value'] = value
    opts = codeinfra.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = codeinfra.runtime.invoke_output('simple-invoke:index:myInvoke', __args__, opts=opts, typ=MyInvokeResult)
    return __ret__.apply(lambda __response__: MyInvokeResult(
        result=codeinfra.get(__response__, 'result')))
