// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * test new feature with resoruces
 */
export class Foo extends codeinfra.CustomResource {
    /**
     * Get an existing Foo resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: codeinfra.Input<codeinfra.ID>, opts?: codeinfra.CustomResourceOptions): Foo {
        return new Foo(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __codeinfraType = 'example:index:Foo';

    /**
     * Returns true if the given object is an instance of Foo.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Foo {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === Foo.__codeinfraType;
    }

    /**
     * A test for plain types
     */
    public /*out*/ readonly defaultKubeClientSettings!: codeinfra.Output<outputs.KubeClientSettings | undefined>;

    /**
     * Create a Foo resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FooArgs, opts?: codeinfra.CustomResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.backupKubeClientSettings === undefined) && !opts.urn) {
                throw new Error("Missing required property 'backupKubeClientSettings'");
            }
            resourceInputs["argument"] = args ? args.argument : undefined;
            resourceInputs["backupKubeClientSettings"] = args ? (args.backupKubeClientSettings ? codeinfra.output(args.backupKubeClientSettings).apply(inputs.kubeClientSettingsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["kubeClientSettings"] = args ? (args.kubeClientSettings ? codeinfra.output(args.kubeClientSettings).apply(inputs.kubeClientSettingsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["settings"] = args ? (args.settings ? codeinfra.output(args.settings).apply(inputs.layeredTypeArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["defaultKubeClientSettings"] = undefined /*out*/;
        } else {
            resourceInputs["defaultKubeClientSettings"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Foo.__codeinfraType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Foo resource.
 */
export interface FooArgs {
    argument?: string;
    /**
     * Options for tuning the Kubernetes client used by a Provider.
     */
    backupKubeClientSettings: codeinfra.Input<inputs.KubeClientSettingsArgs>;
    /**
     * Options for tuning the Kubernetes client used by a Provider.
     */
    kubeClientSettings?: codeinfra.Input<inputs.KubeClientSettingsArgs>;
    /**
     * describing things
     */
    settings?: codeinfra.Input<inputs.LayeredTypeArgs>;
}
