// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"context"
	"reflect"

	"errors"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"secrets/mypkg/internal"
)

type Resource struct {
	codeinfra.CustomResourceState

	Config      ConfigOutput             `codeinfra:"config"`
	ConfigArray ConfigArrayOutput        `codeinfra:"configArray"`
	ConfigMap   ConfigMapOutput          `codeinfra:"configMap"`
	Foo         codeinfra.StringOutput      `codeinfra:"foo"`
	FooArray    codeinfra.StringArrayOutput `codeinfra:"fooArray"`
	FooMap      codeinfra.StringMapOutput   `codeinfra:"fooMap"`
}

// NewResource registers a new resource with the given unique name, arguments, and options.
func NewResource(ctx *codeinfra.Context,
	name string, args *ResourceArgs, opts ...codeinfra.ResourceOption) (*Resource, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Config == nil {
		return nil, errors.New("invalid value for required argument 'Config'")
	}
	if args.ConfigArray == nil {
		return nil, errors.New("invalid value for required argument 'ConfigArray'")
	}
	if args.ConfigMap == nil {
		return nil, errors.New("invalid value for required argument 'ConfigMap'")
	}
	if args.Foo == nil {
		return nil, errors.New("invalid value for required argument 'Foo'")
	}
	if args.FooArray == nil {
		return nil, errors.New("invalid value for required argument 'FooArray'")
	}
	if args.FooMap == nil {
		return nil, errors.New("invalid value for required argument 'FooMap'")
	}
	if args.Config != nil {
		args.Config = codeinfra.ToSecret(args.Config).(ConfigInput)
	}
	if args.ConfigArray != nil {
		args.ConfigArray = codeinfra.ToSecret(args.ConfigArray).(ConfigArrayInput)
	}
	if args.ConfigMap != nil {
		args.ConfigMap = codeinfra.ToSecret(args.ConfigMap).(ConfigMapInput)
	}
	if args.Foo != nil {
		args.Foo = codeinfra.ToSecret(args.Foo).(codeinfra.StringInput)
	}
	if args.FooArray != nil {
		args.FooArray = codeinfra.ToSecret(args.FooArray).(codeinfra.StringArrayInput)
	}
	if args.FooMap != nil {
		args.FooMap = codeinfra.ToSecret(args.FooMap).(codeinfra.StringMapInput)
	}
	secrets := codeinfra.AdditionalSecretOutputs([]string{
		"config",
		"configArray",
		"configMap",
		"foo",
		"fooArray",
		"fooMap",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Resource
	err := ctx.RegisterResource("mypkg::Resource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResource gets an existing Resource resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResource(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *ResourceState, opts ...codeinfra.ResourceOption) (*Resource, error) {
	var resource Resource
	err := ctx.ReadResource("mypkg::Resource", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Resource resources.
type resourceState struct {
}

type ResourceState struct {
}

func (ResourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceState)(nil)).Elem()
}

type resourceArgs struct {
	Config      Config            `codeinfra:"config"`
	ConfigArray []Config          `codeinfra:"configArray"`
	ConfigMap   map[string]Config `codeinfra:"configMap"`
	Foo         string            `codeinfra:"foo"`
	FooArray    []string          `codeinfra:"fooArray"`
	FooMap      map[string]string `codeinfra:"fooMap"`
}

// The set of arguments for constructing a Resource resource.
type ResourceArgs struct {
	Config      ConfigInput
	ConfigArray ConfigArrayInput
	ConfigMap   ConfigMapInput
	Foo         codeinfra.StringInput
	FooArray    codeinfra.StringArrayInput
	FooMap      codeinfra.StringMapInput
}

func (ResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceArgs)(nil)).Elem()
}

type ResourceInput interface {
	codeinfra.Input

	ToResourceOutput() ResourceOutput
	ToResourceOutputWithContext(ctx context.Context) ResourceOutput
}

func (*Resource) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (i *Resource) ToResourceOutput() ResourceOutput {
	return i.ToResourceOutputWithContext(context.Background())
}

func (i *Resource) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(ResourceOutput)
}

func (i *Resource) ToOutput(ctx context.Context) codeinfrax.Output[*Resource] {
	return codeinfrax.Output[*Resource]{
		OutputState: i.ToResourceOutputWithContext(ctx).OutputState,
	}
}

type ResourceOutput struct{ *codeinfra.OutputState }

func (ResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (o ResourceOutput) ToResourceOutput() ResourceOutput {
	return o
}

func (o ResourceOutput) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return o
}

func (o ResourceOutput) ToOutput(ctx context.Context) codeinfrax.Output[*Resource] {
	return codeinfrax.Output[*Resource]{
		OutputState: o.OutputState,
	}
}

func (o ResourceOutput) Config() ConfigOutput {
	return o.ApplyT(func(v *Resource) ConfigOutput { return v.Config }).(ConfigOutput)
}

func (o ResourceOutput) ConfigArray() ConfigArrayOutput {
	return o.ApplyT(func(v *Resource) ConfigArrayOutput { return v.ConfigArray }).(ConfigArrayOutput)
}

func (o ResourceOutput) ConfigMap() ConfigMapOutput {
	return o.ApplyT(func(v *Resource) ConfigMapOutput { return v.ConfigMap }).(ConfigMapOutput)
}

func (o ResourceOutput) Foo() codeinfra.StringOutput {
	return o.ApplyT(func(v *Resource) codeinfra.StringOutput { return v.Foo }).(codeinfra.StringOutput)
}

func (o ResourceOutput) FooArray() codeinfra.StringArrayOutput {
	return o.ApplyT(func(v *Resource) codeinfra.StringArrayOutput { return v.FooArray }).(codeinfra.StringArrayOutput)
}

func (o ResourceOutput) FooMap() codeinfra.StringMapOutput {
	return o.ApplyT(func(v *Resource) codeinfra.StringMapOutput { return v.FooMap }).(codeinfra.StringMapOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*ResourceInput)(nil)).Elem(), &Resource{})
	codeinfra.RegisterOutputType(ResourceOutput{})
}
