// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"errors"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"plain-object-disable-defaults/example/internal"
)

// test new feature with resoruces
type Foo struct {
	codeinfra.CustomResourceState

	// A test for plain types
	DefaultKubeClientSettings KubeClientSettingsPtrOutput `codeinfra:"defaultKubeClientSettings"`
}

// NewFoo registers a new resource with the given unique name, arguments, and options.
func NewFoo(ctx *codeinfra.Context,
	name string, args *FooArgs, opts ...codeinfra.ResourceOption) (*Foo, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BackupKubeClientSettings == nil {
		return nil, errors.New("invalid value for required argument 'BackupKubeClientSettings'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Foo
	err := ctx.RegisterResource("example:index:Foo", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFoo gets an existing Foo resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFoo(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *FooState, opts ...codeinfra.ResourceOption) (*Foo, error) {
	var resource Foo
	err := ctx.ReadResource("example:index:Foo", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Foo resources.
type fooState struct {
}

type FooState struct {
}

func (FooState) ElementType() reflect.Type {
	return reflect.TypeOf((*fooState)(nil)).Elem()
}

type fooArgs struct {
	Argument *string `codeinfra:"argument"`
	// Options for tuning the Kubernetes client used by a Provider.
	BackupKubeClientSettings KubeClientSettings `codeinfra:"backupKubeClientSettings"`
	// Options for tuning the Kubernetes client used by a Provider.
	KubeClientSettings *KubeClientSettings `codeinfra:"kubeClientSettings"`
	// describing things
	Settings *LayeredType `codeinfra:"settings"`
}

// The set of arguments for constructing a Foo resource.
type FooArgs struct {
	Argument *string
	// Options for tuning the Kubernetes client used by a Provider.
	BackupKubeClientSettings KubeClientSettingsInput
	// Options for tuning the Kubernetes client used by a Provider.
	KubeClientSettings KubeClientSettingsPtrInput
	// describing things
	Settings LayeredTypePtrInput
}

func (FooArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fooArgs)(nil)).Elem()
}

type FooInput interface {
	codeinfra.Input

	ToFooOutput() FooOutput
	ToFooOutputWithContext(ctx context.Context) FooOutput
}

func (*Foo) ElementType() reflect.Type {
	return reflect.TypeOf((**Foo)(nil)).Elem()
}

func (i *Foo) ToFooOutput() FooOutput {
	return i.ToFooOutputWithContext(context.Background())
}

func (i *Foo) ToFooOutputWithContext(ctx context.Context) FooOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(FooOutput)
}

type FooOutput struct{ *codeinfra.OutputState }

func (FooOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Foo)(nil)).Elem()
}

func (o FooOutput) ToFooOutput() FooOutput {
	return o
}

func (o FooOutput) ToFooOutputWithContext(ctx context.Context) FooOutput {
	return o
}

// A test for plain types
func (o FooOutput) DefaultKubeClientSettings() KubeClientSettingsPtrOutput {
	return o.ApplyT(func(v *Foo) KubeClientSettingsPtrOutput { return v.DefaultKubeClientSettings }).(KubeClientSettingsPtrOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*FooInput)(nil)).Elem(), &Foo{})
	codeinfra.RegisterOutputType(FooOutput{})
}
