# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'FuncWithSecretsResult',
    'AwaitableFuncWithSecretsResult',
    'func_with_secrets',
    'func_with_secrets_output',
]

@codeinfra.output_type
class FuncWithSecretsResult:
    def __init__(__self__, ciphertext=None, crypto_key=None, id=None, plaintext=None):
        if ciphertext and not isinstance(ciphertext, str):
            raise TypeError("Expected argument 'ciphertext' to be a str")
        codeinfra.set(__self__, "ciphertext", ciphertext)
        if crypto_key and not isinstance(crypto_key, str):
            raise TypeError("Expected argument 'crypto_key' to be a str")
        codeinfra.set(__self__, "crypto_key", crypto_key)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        codeinfra.set(__self__, "id", id)
        if plaintext and not isinstance(plaintext, str):
            raise TypeError("Expected argument 'plaintext' to be a str")
        codeinfra.set(__self__, "plaintext", plaintext)

    @property
    @codeinfra.getter
    def ciphertext(self) -> str:
        return codeinfra.get(self, "ciphertext")

    @property
    @codeinfra.getter(name="cryptoKey")
    def crypto_key(self) -> str:
        return codeinfra.get(self, "crypto_key")

    @property
    @codeinfra.getter
    def id(self) -> str:
        return codeinfra.get(self, "id")

    @property
    @codeinfra.getter
    def plaintext(self) -> str:
        return codeinfra.get(self, "plaintext")


class AwaitableFuncWithSecretsResult(FuncWithSecretsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return FuncWithSecretsResult(
            ciphertext=self.ciphertext,
            crypto_key=self.crypto_key,
            id=self.id,
            plaintext=self.plaintext)


def func_with_secrets(crypto_key: Optional[str] = None,
                      plaintext: Optional[str] = None,
                      opts: Optional[codeinfra.InvokeOptions] = None) -> AwaitableFuncWithSecretsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['cryptoKey'] = crypto_key
    __args__['plaintext'] = plaintext
    opts = codeinfra.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = codeinfra.runtime.invoke('mypkg::funcWithSecrets', __args__, opts=opts, typ=FuncWithSecretsResult).value

    return AwaitableFuncWithSecretsResult(
        ciphertext=codeinfra.get(__ret__, 'ciphertext'),
        crypto_key=codeinfra.get(__ret__, 'crypto_key'),
        id=codeinfra.get(__ret__, 'id'),
        plaintext=codeinfra.get(__ret__, 'plaintext'))
def func_with_secrets_output(crypto_key: Optional[codeinfra.Input[str]] = None,
                             plaintext: Optional[codeinfra.Input[str]] = None,
                             opts: Optional[Union[codeinfra.InvokeOptions, codeinfra.InvokeOutputOptions]] = None) -> codeinfra.Output[FuncWithSecretsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['cryptoKey'] = crypto_key
    __args__['plaintext'] = plaintext
    opts = codeinfra.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = codeinfra.runtime.invoke_output('mypkg::funcWithSecrets', __args__, opts=opts, typ=FuncWithSecretsResult)
    return __ret__.apply(lambda __response__: FuncWithSecretsResult(
        ciphertext=codeinfra.get(__response__, 'ciphertext'),
        crypto_key=codeinfra.get(__response__, 'crypto_key'),
        id=codeinfra.get(__response__, 'id'),
        plaintext=codeinfra.get(__response__, 'plaintext')))
