// *** WARNING: this file was generated by codeinfra-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

export class Resource extends codeinfra.CustomResource {
    /**
     * Get an existing Resource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: codeinfra.Input<codeinfra.ID>, opts?: codeinfra.CustomResourceOptions): Resource {
        return new Resource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __codeinfraType = 'primitive:index:Resource';

    /**
     * Returns true if the given object is an instance of Resource.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Resource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === Resource.__codeinfraType;
    }

    public readonly boolean!: codeinfra.Output<boolean>;
    public readonly booleanMap!: codeinfra.Output<{[key: string]: boolean}>;
    public readonly float!: codeinfra.Output<number>;
    public readonly integer!: codeinfra.Output<number>;
    public readonly numberArray!: codeinfra.Output<number[]>;
    public readonly string!: codeinfra.Output<string>;

    /**
     * Create a Resource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceArgs, opts?: codeinfra.CustomResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.boolean === undefined) && !opts.urn) {
                throw new Error("Missing required property 'boolean'");
            }
            if ((!args || args.booleanMap === undefined) && !opts.urn) {
                throw new Error("Missing required property 'booleanMap'");
            }
            if ((!args || args.float === undefined) && !opts.urn) {
                throw new Error("Missing required property 'float'");
            }
            if ((!args || args.integer === undefined) && !opts.urn) {
                throw new Error("Missing required property 'integer'");
            }
            if ((!args || args.numberArray === undefined) && !opts.urn) {
                throw new Error("Missing required property 'numberArray'");
            }
            if ((!args || args.string === undefined) && !opts.urn) {
                throw new Error("Missing required property 'string'");
            }
            resourceInputs["boolean"] = args ? args.boolean : undefined;
            resourceInputs["booleanMap"] = args ? args.booleanMap : undefined;
            resourceInputs["float"] = args ? args.float : undefined;
            resourceInputs["integer"] = args ? args.integer : undefined;
            resourceInputs["numberArray"] = args ? args.numberArray : undefined;
            resourceInputs["string"] = args ? args.string : undefined;
        } else {
            resourceInputs["boolean"] = undefined /*out*/;
            resourceInputs["booleanMap"] = undefined /*out*/;
            resourceInputs["float"] = undefined /*out*/;
            resourceInputs["integer"] = undefined /*out*/;
            resourceInputs["numberArray"] = undefined /*out*/;
            resourceInputs["string"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Resource.__codeinfraType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Resource resource.
 */
export interface ResourceArgs {
    boolean: codeinfra.Input<boolean>;
    booleanMap: codeinfra.Input<{[key: string]: codeinfra.Input<boolean>}>;
    float: codeinfra.Input<number>;
    integer: codeinfra.Input<number>;
    numberArray: codeinfra.Input<codeinfra.Input<number>[]>;
    string: codeinfra.Input<string>;
}
