# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities

__all__ = [
    'ENIConfigSpecArgs',
    'ENIConfigSpecArgsDict',
]

MYPY = False

if not MYPY:
    class ENIConfigSpecArgsDict(TypedDict):
        security_groups: NotRequired[codeinfra.Input[Sequence[codeinfra.Input[str]]]]
        subnet: NotRequired[codeinfra.Input[str]]
elif False:
    ENIConfigSpecArgsDict: TypeAlias = Mapping[str, Any]

@codeinfra.input_type
class ENIConfigSpecArgs:
    def __init__(__self__, *,
                 security_groups: Optional[codeinfra.Input[Sequence[codeinfra.Input[str]]]] = None,
                 subnet: Optional[codeinfra.Input[str]] = None):
        if security_groups is not None:
            codeinfra.set(__self__, "security_groups", security_groups)
        if subnet is not None:
            codeinfra.set(__self__, "subnet", subnet)

    @property
    @codeinfra.getter(name="securityGroups")
    def security_groups(self) -> Optional[codeinfra.Input[Sequence[codeinfra.Input[str]]]]:
        return codeinfra.get(self, "security_groups")

    @security_groups.setter
    def security_groups(self, value: Optional[codeinfra.Input[Sequence[codeinfra.Input[str]]]]):
        codeinfra.set(self, "security_groups", value)

    @property
    @codeinfra.getter
    def subnet(self) -> Optional[codeinfra.Input[str]]:
        return codeinfra.get(self, "subnet")

    @subnet.setter
    def subnet(self, value: Optional[codeinfra.Input[str]]):
        codeinfra.set(self, "subnet", value)


