// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foo

import (
	"context"
	"reflect"

	"errors"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"plain-and-default/foo/internal"
)

type ModuleResource struct {
	codeinfra.CustomResourceState

	OptionalBool codeinfrax.Output[*bool] `codeinfra:"optionalBool"`
}

// NewModuleResource registers a new resource with the given unique name, arguments, and options.
func NewModuleResource(ctx *codeinfra.Context,
	name string, args *ModuleResourceArgs, opts ...codeinfra.ResourceOption) (*ModuleResource, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OptionalBool == nil {
		args.OptionalBool = codeinfrax.Ptr(true)
	}
	args.OptionalConst = codeinfrax.Ptr("val")
	if args.OptionalEnum == nil {
		args.OptionalEnum = codeinfrax.Ptr(EnumThing(8))
	}
	if args.OptionalNumber == nil {
		args.OptionalNumber = codeinfrax.Ptr(42.0)
	}
	if args.OptionalString == nil {
		args.OptionalString = codeinfrax.Ptr("buzzer")
	}
	if args.PlainOptionalBool == nil {
		plainOptionalBool_ := true
		args.PlainOptionalBool = &plainOptionalBool_
	}
	plainOptionalConst_ := "val"
	args.PlainOptionalConst = &plainOptionalConst_
	if args.PlainOptionalNumber == nil {
		plainOptionalNumber_ := 42.0
		args.PlainOptionalNumber = &plainOptionalNumber_
	}
	if args.PlainOptionalString == nil {
		plainOptionalString_ := "buzzer"
		args.PlainOptionalString = &plainOptionalString_
	}
	if internal.IsZero(args.PlainRequiredBool) {
		args.PlainRequiredBool = true
	}
	args.PlainRequiredConst = "val"
	if internal.IsZero(args.PlainRequiredNumber) {
		args.PlainRequiredNumber = 42.0
	}
	if internal.IsZero(args.PlainRequiredString) {
		args.PlainRequiredString = "buzzer"
	}
	if args.RequiredBool == nil {
		args.RequiredBool = codeinfrax.Val(true)
	}
	if args.RequiredEnum == nil {
		args.RequiredEnum = codeinfrax.Val(EnumThing(4))
	}
	if args.RequiredNumber == nil {
		args.RequiredNumber = codeinfrax.Val(42.0)
	}
	if args.RequiredString == nil {
		args.RequiredString = codeinfrax.Val("buzzer")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ModuleResource
	err := ctx.RegisterResource("foobar::ModuleResource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetModuleResource gets an existing ModuleResource resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetModuleResource(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *ModuleResourceState, opts ...codeinfra.ResourceOption) (*ModuleResource, error) {
	var resource ModuleResource
	err := ctx.ReadResource("foobar::ModuleResource", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ModuleResource resources.
type moduleResourceState struct {
}

type ModuleResourceState struct {
}

func (ModuleResourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*moduleResourceState)(nil)).Elem()
}

type moduleResourceArgs struct {
	OptionalBool        *bool      `codeinfra:"optionalBool"`
	OptionalConst       *string    `codeinfra:"optionalConst"`
	OptionalEnum        *EnumThing `codeinfra:"optionalEnum"`
	OptionalNumber      *float64   `codeinfra:"optionalNumber"`
	OptionalString      *string    `codeinfra:"optionalString"`
	PlainOptionalBool   *bool      `codeinfra:"plainOptionalBool"`
	PlainOptionalConst  *string    `codeinfra:"plainOptionalConst"`
	PlainOptionalNumber *float64   `codeinfra:"plainOptionalNumber"`
	PlainOptionalString *string    `codeinfra:"plainOptionalString"`
	PlainRequiredBool   bool       `codeinfra:"plainRequiredBool"`
	PlainRequiredConst  string     `codeinfra:"plainRequiredConst"`
	PlainRequiredNumber float64    `codeinfra:"plainRequiredNumber"`
	PlainRequiredString string     `codeinfra:"plainRequiredString"`
	RequiredBool        bool       `codeinfra:"requiredBool"`
	RequiredEnum        EnumThing  `codeinfra:"requiredEnum"`
	RequiredNumber      float64    `codeinfra:"requiredNumber"`
	RequiredString      string     `codeinfra:"requiredString"`
}

// The set of arguments for constructing a ModuleResource resource.
type ModuleResourceArgs struct {
	OptionalBool        codeinfrax.Input[*bool]
	OptionalConst       codeinfrax.Input[*string]
	OptionalEnum        codeinfrax.Input[*EnumThing]
	OptionalNumber      codeinfrax.Input[*float64]
	OptionalString      codeinfrax.Input[*string]
	PlainOptionalBool   *bool
	PlainOptionalConst  *string
	PlainOptionalNumber *float64
	PlainOptionalString *string
	PlainRequiredBool   bool
	PlainRequiredConst  string
	PlainRequiredNumber float64
	PlainRequiredString string
	RequiredBool        codeinfrax.Input[bool]
	RequiredEnum        codeinfrax.Input[EnumThing]
	RequiredNumber      codeinfrax.Input[float64]
	RequiredString      codeinfrax.Input[string]
}

func (ModuleResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*moduleResourceArgs)(nil)).Elem()
}

type ModuleResourceOutput struct{ *codeinfra.OutputState }

func (ModuleResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ModuleResource)(nil)).Elem()
}

func (o ModuleResourceOutput) ToModuleResourceOutput() ModuleResourceOutput {
	return o
}

func (o ModuleResourceOutput) ToModuleResourceOutputWithContext(ctx context.Context) ModuleResourceOutput {
	return o
}

func (o ModuleResourceOutput) ToOutput(ctx context.Context) codeinfrax.Output[ModuleResource] {
	return codeinfrax.Output[ModuleResource]{
		OutputState: o.OutputState,
	}
}

func (o ModuleResourceOutput) OptionalBool() codeinfrax.Output[*bool] {
	value := codeinfrax.Apply[ModuleResource](o, func(v ModuleResource) codeinfrax.Output[*bool] { return v.OptionalBool })
	return codeinfrax.Flatten[*bool, codeinfrax.Output[*bool]](value)
}

func init() {
	codeinfra.RegisterOutputType(ModuleResourceOutput{})
}
