// Code generated by codeinfra-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package subpackage

import (
	"context"
	"reflect"

	"example.com/codeinfra-subpackage/sdk/go/v2/subpackage/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

type HelloWorld struct {
	codeinfra.CustomResourceState

	ParameterValue codeinfra.StringOutput `codeinfra:"parameterValue"`
}

// NewHelloWorld registers a new resource with the given unique name, arguments, and options.
func NewHelloWorld(ctx *codeinfra.Context,
	name string, args *HelloWorldArgs, opts ...codeinfra.ResourceOption) (*HelloWorld, error) {
	if args == nil {
		args = &HelloWorldArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource HelloWorld
	err = ctx.RegisterPackageResource("subpackage:index:HelloWorld", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHelloWorld gets an existing HelloWorld resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHelloWorld(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *HelloWorldState, opts ...codeinfra.ResourceOption) (*HelloWorld, error) {
	var resource HelloWorld
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("subpackage:index:HelloWorld", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HelloWorld resources.
type helloWorldState struct {
}

type HelloWorldState struct {
}

func (HelloWorldState) ElementType() reflect.Type {
	return reflect.TypeOf((*helloWorldState)(nil)).Elem()
}

type helloWorldArgs struct {
}

// The set of arguments for constructing a HelloWorld resource.
type HelloWorldArgs struct {
}

func (HelloWorldArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*helloWorldArgs)(nil)).Elem()
}

type HelloWorldInput interface {
	codeinfra.Input

	ToHelloWorldOutput() HelloWorldOutput
	ToHelloWorldOutputWithContext(ctx context.Context) HelloWorldOutput
}

func (*HelloWorld) ElementType() reflect.Type {
	return reflect.TypeOf((**HelloWorld)(nil)).Elem()
}

func (i *HelloWorld) ToHelloWorldOutput() HelloWorldOutput {
	return i.ToHelloWorldOutputWithContext(context.Background())
}

func (i *HelloWorld) ToHelloWorldOutputWithContext(ctx context.Context) HelloWorldOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(HelloWorldOutput)
}

type HelloWorldOutput struct{ *codeinfra.OutputState }

func (HelloWorldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HelloWorld)(nil)).Elem()
}

func (o HelloWorldOutput) ToHelloWorldOutput() HelloWorldOutput {
	return o
}

func (o HelloWorldOutput) ToHelloWorldOutputWithContext(ctx context.Context) HelloWorldOutput {
	return o
}

func (o HelloWorldOutput) ParameterValue() codeinfra.StringOutput {
	return o.ApplyT(func(v *HelloWorld) codeinfra.StringOutput { return v.ParameterValue }).(codeinfra.StringOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*HelloWorldInput)(nil)).Elem(), &HelloWorld{})
	codeinfra.RegisterOutputType(HelloWorldOutput{})
}
