// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetAmiIdsFilter {
    name: string;
    values: string[];
}

export interface GetAmiIdsFilterArgs {
    name: codeinfra.Input<string>;
    values: codeinfra.Input<codeinfra.Input<string>[]>;
}

