# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from .resource import Resource

__all__ = [
    'ArgFunctionResult',
    'AwaitableArgFunctionResult',
    'arg_function',
    'arg_function_output',
]

@codeinfra.output_type
class ArgFunctionResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, Resource):
            raise TypeError("Expected argument 'result' to be a Resource")
        codeinfra.set(__self__, "result", result)

    @property
    @codeinfra.getter
    def result(self) -> Optional['Resource']:
        return codeinfra.get(self, "result")


class AwaitableArgFunctionResult(ArgFunctionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ArgFunctionResult(
            result=self.result)


def arg_function(arg1: Optional['Resource'] = None,
                 opts: Optional[codeinfra.InvokeOptions] = None) -> AwaitableArgFunctionResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['arg1'] = arg1
    opts = codeinfra.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = codeinfra.runtime.invoke('example::argFunction', __args__, opts=opts, typ=ArgFunctionResult).value

    return AwaitableArgFunctionResult(
        result=codeinfra.get(__ret__, 'result'))
def arg_function_output(arg1: Optional[codeinfra.Input[Optional['Resource']]] = None,
                        opts: Optional[Union[codeinfra.InvokeOptions, codeinfra.InvokeOutputOptions]] = None) -> codeinfra.Output[ArgFunctionResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['arg1'] = arg1
    opts = codeinfra.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = codeinfra.runtime.invoke_output('example::argFunction', __args__, opts=opts, typ=ArgFunctionResult)
    return __ret__.apply(lambda __response__: ArgFunctionResult(
        result=codeinfra.get(__response__, 'result')))
