// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

import {Resource} from "./index";

export function argFunction(args?: ArgFunctionArgs, opts?: codeinfra.InvokeOptions): Promise<ArgFunctionResult> {
    args = args || {};
    opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return codeinfra.runtime.invoke("example::argFunction", {
        "arg1": args.arg1,
    }, opts);
}

export interface ArgFunctionArgs {
    arg1?: Resource;
}

export interface ArgFunctionResult {
    readonly result?: Resource;
}
export function argFunctionOutput(args?: ArgFunctionOutputArgs, opts?: codeinfra.InvokeOutputOptions): codeinfra.Output<ArgFunctionResult> {
    args = args || {};
    opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return codeinfra.runtime.invokeOutput("example::argFunction", {
        "arg1": args.arg1,
    }, opts);
}

export interface ArgFunctionOutputArgs {
    arg1?: codeinfra.Input<Resource>;
}
