// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

import * as codeinfraAws from "@codeinfra/aws";
import * as codeinfraKubernetes from "@codeinfra/kubernetes";

export class Component extends codeinfra.CustomResource {
    /**
     * Get an existing Component resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: codeinfra.Input<codeinfra.ID>, opts?: codeinfra.CustomResourceOptions): Component {
        return new Component(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __codeinfraType = 'example::Component';

    /**
     * Returns true if the given object is an instance of Component.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Component {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === Component.__codeinfraType;
    }

    public /*out*/ readonly provider!: codeinfra.Output<codeinfraKubernetes.Provider | undefined>;
    public /*out*/ readonly securityGroup!: codeinfra.Output<codeinfraAws.ec2.SecurityGroup>;
    public /*out*/ readonly storageClasses!: codeinfra.Output<{[key: string]: codeinfraKubernetes.storage.v1.StorageClass} | undefined>;

    /**
     * Create a Component resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ComponentArgs, opts?: codeinfra.CustomResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.requiredMetadata === undefined) && !opts.urn) {
                throw new Error("Missing required property 'requiredMetadata'");
            }
            if ((!args || args.requiredMetadataArray === undefined) && !opts.urn) {
                throw new Error("Missing required property 'requiredMetadataArray'");
            }
            if ((!args || args.requiredMetadataMap === undefined) && !opts.urn) {
                throw new Error("Missing required property 'requiredMetadataMap'");
            }
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["metadataArray"] = args ? args.metadataArray : undefined;
            resourceInputs["metadataMap"] = args ? args.metadataMap : undefined;
            resourceInputs["requiredMetadata"] = args ? args.requiredMetadata : undefined;
            resourceInputs["requiredMetadataArray"] = args ? args.requiredMetadataArray : undefined;
            resourceInputs["requiredMetadataMap"] = args ? args.requiredMetadataMap : undefined;
            resourceInputs["provider"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["storageClasses"] = undefined /*out*/;
        } else {
            resourceInputs["provider"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["storageClasses"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Component.__codeinfraType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Component resource.
 */
export interface ComponentArgs {
    metadata?: codeinfra.Input<codeinfraKubernetes.types.input.meta.v1.ObjectMeta>;
    metadataArray?: codeinfra.Input<codeinfra.Input<codeinfraKubernetes.types.input.meta.v1.ObjectMeta>[]>;
    metadataMap?: codeinfra.Input<{[key: string]: codeinfra.Input<codeinfraKubernetes.types.input.meta.v1.ObjectMeta>}>;
    requiredMetadata: codeinfra.Input<codeinfraKubernetes.types.input.meta.v1.ObjectMeta>;
    requiredMetadataArray: codeinfra.Input<codeinfra.Input<codeinfraKubernetes.types.input.meta.v1.ObjectMeta>[]>;
    requiredMetadataMap: codeinfra.Input<{[key: string]: codeinfra.Input<codeinfraKubernetes.types.input.meta.v1.ObjectMeta>}>;
}
