// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"simple-plain-schema-go-generics-only/example/internal"
)

var _ = internal.GetEnvOrDefault

type Foo struct {
	A bool    `codeinfra:"a"`
	B *bool   `codeinfra:"b"`
	C int     `codeinfra:"c"`
	D *int    `codeinfra:"d"`
	E string  `codeinfra:"e"`
	F *string `codeinfra:"f"`
}

type FooArgs struct {
	A bool    `codeinfra:"a"`
	B *bool   `codeinfra:"b"`
	C int     `codeinfra:"c"`
	D *int    `codeinfra:"d"`
	E string  `codeinfra:"e"`
	F *string `codeinfra:"f"`
}

func (FooArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Foo)(nil)).Elem()
}

func (i FooArgs) ToFooOutput() FooOutput {
	return i.ToFooOutputWithContext(context.Background())
}

func (i FooArgs) ToFooOutputWithContext(ctx context.Context) FooOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(FooOutput)
}

func (i *FooArgs) ToOutput(ctx context.Context) codeinfrax.Output[*FooArgs] {
	return codeinfrax.Val(i)
}

type FooOutput struct{ *codeinfra.OutputState }

func (FooOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Foo)(nil)).Elem()
}

func (o FooOutput) ToFooOutput() FooOutput {
	return o
}

func (o FooOutput) ToFooOutputWithContext(ctx context.Context) FooOutput {
	return o
}

func (o FooOutput) ToOutput(ctx context.Context) codeinfrax.Output[Foo] {
	return codeinfrax.Output[Foo]{
		OutputState: o.OutputState,
	}
}

func (o FooOutput) A() codeinfrax.Output[bool] {
	return codeinfrax.Apply[Foo](o, func(v Foo) bool { return v.A })
}

func (o FooOutput) B() codeinfrax.Output[*bool] {
	return codeinfrax.Apply[Foo](o, func(v Foo) *bool { return v.B })
}

func (o FooOutput) C() codeinfrax.Output[int] {
	return codeinfrax.Apply[Foo](o, func(v Foo) int { return v.C })
}

func (o FooOutput) D() codeinfrax.Output[*int] {
	return codeinfrax.Apply[Foo](o, func(v Foo) *int { return v.D })
}

func (o FooOutput) E() codeinfrax.Output[string] {
	return codeinfrax.Apply[Foo](o, func(v Foo) string { return v.E })
}

func (o FooOutput) F() codeinfrax.Output[*string] {
	return codeinfrax.Apply[Foo](o, func(v Foo) *string { return v.F })
}

func init() {
	codeinfra.RegisterOutputType(FooOutput{})
}
