// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"errors"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"simple-plain-schema-go-generics-only/example/internal"
)

type Component struct {
	codeinfra.ResourceState

	A   codeinfrax.Output[bool]                 `codeinfra:"a"`
	B   codeinfrax.Output[*bool]                `codeinfra:"b"`
	Bar codeinfrax.GPtrOutput[Foo, FooOutput]   `codeinfra:"bar"`
	Baz codeinfrax.GArrayOutput[Foo, FooOutput] `codeinfra:"baz"`
	C   codeinfrax.Output[int]                  `codeinfra:"c"`
	D   codeinfrax.Output[*int]                 `codeinfra:"d"`
	E   codeinfrax.Output[string]               `codeinfra:"e"`
	F   codeinfrax.Output[*string]              `codeinfra:"f"`
	Foo codeinfrax.GPtrOutput[Foo, FooOutput]   `codeinfra:"foo"`
}

// NewComponent registers a new resource with the given unique name, arguments, and options.
func NewComponent(ctx *codeinfra.Context,
	name string, args *ComponentArgs, opts ...codeinfra.ResourceOption) (*Component, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Component
	err := ctx.RegisterRemoteComponentResource("example::Component", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type componentArgs struct {
	A      bool           `codeinfra:"a"`
	B      *bool          `codeinfra:"b"`
	Bar    *Foo           `codeinfra:"bar"`
	Baz    []Foo          `codeinfra:"baz"`
	BazMap map[string]Foo `codeinfra:"bazMap"`
	C      int            `codeinfra:"c"`
	D      *int           `codeinfra:"d"`
	E      string         `codeinfra:"e"`
	F      *string        `codeinfra:"f"`
	Foo    *Foo           `codeinfra:"foo"`
}

// The set of arguments for constructing a Component resource.
type ComponentArgs struct {
	A      bool
	B      *bool
	Bar    *Foo
	Baz    []Foo
	BazMap map[string]Foo
	C      int
	D      *int
	E      string
	F      *string
	Foo    codeinfrax.Input[*FooArgs]
}

func (ComponentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*componentArgs)(nil)).Elem()
}

type ComponentOutput struct{ *codeinfra.OutputState }

func (ComponentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Component)(nil)).Elem()
}

func (o ComponentOutput) ToComponentOutput() ComponentOutput {
	return o
}

func (o ComponentOutput) ToComponentOutputWithContext(ctx context.Context) ComponentOutput {
	return o
}

func (o ComponentOutput) ToOutput(ctx context.Context) codeinfrax.Output[Component] {
	return codeinfrax.Output[Component]{
		OutputState: o.OutputState,
	}
}

func (o ComponentOutput) A() codeinfrax.Output[bool] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.Output[bool] { return v.A })
	return codeinfrax.Flatten[bool, codeinfrax.Output[bool]](value)
}

func (o ComponentOutput) B() codeinfrax.Output[*bool] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.Output[*bool] { return v.B })
	return codeinfrax.Flatten[*bool, codeinfrax.Output[*bool]](value)
}

func (o ComponentOutput) Bar() codeinfrax.GPtrOutput[Foo, FooOutput] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.GPtrOutput[Foo, FooOutput] { return v.Bar })
	unwrapped := codeinfrax.Flatten[*Foo, codeinfrax.GPtrOutput[Foo, FooOutput]](value)
	return codeinfrax.GPtrOutput[Foo, FooOutput]{OutputState: unwrapped.OutputState}
}

func (o ComponentOutput) Baz() codeinfrax.GArrayOutput[Foo, FooOutput] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.GArrayOutput[Foo, FooOutput] { return v.Baz })
	unwrapped := codeinfrax.Flatten[[]Foo, codeinfrax.GArrayOutput[Foo, FooOutput]](value)
	return codeinfrax.GArrayOutput[Foo, FooOutput]{OutputState: unwrapped.OutputState}
}

func (o ComponentOutput) C() codeinfrax.Output[int] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.Output[int] { return v.C })
	return codeinfrax.Flatten[int, codeinfrax.Output[int]](value)
}

func (o ComponentOutput) D() codeinfrax.Output[*int] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.Output[*int] { return v.D })
	return codeinfrax.Flatten[*int, codeinfrax.Output[*int]](value)
}

func (o ComponentOutput) E() codeinfrax.Output[string] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.Output[string] { return v.E })
	return codeinfrax.Flatten[string, codeinfrax.Output[string]](value)
}

func (o ComponentOutput) F() codeinfrax.Output[*string] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.Output[*string] { return v.F })
	return codeinfrax.Flatten[*string, codeinfrax.Output[*string]](value)
}

func (o ComponentOutput) Foo() codeinfrax.GPtrOutput[Foo, FooOutput] {
	value := codeinfrax.Apply[Component](o, func(v Component) codeinfrax.GPtrOutput[Foo, FooOutput] { return v.Foo })
	unwrapped := codeinfrax.Flatten[*Foo, codeinfrax.GPtrOutput[Foo, FooOutput]](value)
	return codeinfrax.GPtrOutput[Foo, FooOutput]{OutputState: unwrapped.OutputState}
}

func init() {
	codeinfra.RegisterOutputType(ComponentOutput{})
}
