// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"output-funcs/mypkg/internal"
)

// Check codegen of functions with all optional inputs.
func FuncWithAllOptionalInputs(ctx *codeinfra.Context, args *FuncWithAllOptionalInputsArgs, opts ...codeinfra.InvokeOption) (*FuncWithAllOptionalInputsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv FuncWithAllOptionalInputsResult
	err := ctx.Invoke("mypkg::funcWithAllOptionalInputs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type FuncWithAllOptionalInputsArgs struct {
	// Property A
	A *string `codeinfra:"a"`
	// Property B
	B *string `codeinfra:"b"`
}

type FuncWithAllOptionalInputsResult struct {
	R string `codeinfra:"r"`
}

func FuncWithAllOptionalInputsOutput(ctx *codeinfra.Context, args FuncWithAllOptionalInputsOutputArgs, opts ...codeinfra.InvokeOption) FuncWithAllOptionalInputsResultOutput {
	outputResult := codeinfrax.ApplyErr[*FuncWithAllOptionalInputsArgs](args.ToOutput(), func(plainArgs *FuncWithAllOptionalInputsArgs) (*FuncWithAllOptionalInputsResult, error) {
		return FuncWithAllOptionalInputs(ctx, plainArgs, opts...)
	})

	return codeinfrax.Cast[FuncWithAllOptionalInputsResultOutput, *FuncWithAllOptionalInputsResult](outputResult)
}

type FuncWithAllOptionalInputsOutputArgs struct {
	// Property A
	A codeinfrax.Input[*string] `codeinfra:"a"`
	// Property B
	B codeinfrax.Input[*string] `codeinfra:"b"`
}

func (args FuncWithAllOptionalInputsOutputArgs) ToOutput() codeinfrax.Output[*FuncWithAllOptionalInputsArgs] {
	allArgs := codeinfrax.All(
		args.A.ToOutput(context.Background()).AsAny(),
		args.B.ToOutput(context.Background()).AsAny())
	return codeinfrax.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *FuncWithAllOptionalInputsArgs {
		return &FuncWithAllOptionalInputsArgs{
			A: resolvedArgs[0].(*string),
			B: resolvedArgs[1].(*string),
		}
	})
}

type FuncWithAllOptionalInputsResultOutput struct{ *codeinfra.OutputState }

func (FuncWithAllOptionalInputsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FuncWithAllOptionalInputsResult)(nil)).Elem()
}

func (o FuncWithAllOptionalInputsResultOutput) ToOutput(context.Context) codeinfrax.Output[*FuncWithAllOptionalInputsResult] {
	return codeinfrax.Output[*FuncWithAllOptionalInputsResult]{
		OutputState: o.OutputState,
	}
}

func (o FuncWithAllOptionalInputsResultOutput) R() codeinfrax.Output[string] {
	return codeinfrax.Apply[*FuncWithAllOptionalInputsResult](o, func(v *FuncWithAllOptionalInputsResult) string { return v.R })
}
