// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"context"
	"reflect"

	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfrax"
	"output-funcs/mypkg/internal"
)

// Check codegen of functions with a List parameter.
func FuncWithListParam(ctx *codeinfra.Context, args *FuncWithListParamArgs, opts ...codeinfra.InvokeOption) (*FuncWithListParamResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv FuncWithListParamResult
	err := ctx.Invoke("mypkg::funcWithListParam", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type FuncWithListParamArgs struct {
	A []string `codeinfra:"a"`
	B *string  `codeinfra:"b"`
}

type FuncWithListParamResult struct {
	R string `codeinfra:"r"`
}

func FuncWithListParamOutput(ctx *codeinfra.Context, args FuncWithListParamOutputArgs, opts ...codeinfra.InvokeOption) FuncWithListParamResultOutput {
	outputResult := codeinfrax.ApplyErr[*FuncWithListParamArgs](args.ToOutput(), func(plainArgs *FuncWithListParamArgs) (*FuncWithListParamResult, error) {
		return FuncWithListParam(ctx, plainArgs, opts...)
	})

	return codeinfrax.Cast[FuncWithListParamResultOutput, *FuncWithListParamResult](outputResult)
}

type FuncWithListParamOutputArgs struct {
	A codeinfrax.Input[[]string] `codeinfra:"a"`
	B codeinfrax.Input[*string]  `codeinfra:"b"`
}

func (args FuncWithListParamOutputArgs) ToOutput() codeinfrax.Output[*FuncWithListParamArgs] {
	allArgs := codeinfrax.All(
		args.A.ToOutput(context.Background()).AsAny(),
		args.B.ToOutput(context.Background()).AsAny())
	return codeinfrax.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *FuncWithListParamArgs {
		return &FuncWithListParamArgs{
			A: resolvedArgs[0].([]string),
			B: resolvedArgs[1].(*string),
		}
	})
}

type FuncWithListParamResultOutput struct{ *codeinfra.OutputState }

func (FuncWithListParamResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FuncWithListParamResult)(nil)).Elem()
}

func (o FuncWithListParamResultOutput) ToOutput(context.Context) codeinfrax.Output[*FuncWithListParamResult] {
	return codeinfrax.Output[*FuncWithListParamResult]{
		OutputState: o.OutputState,
	}
}

func (o FuncWithListParamResultOutput) R() codeinfrax.Output[string] {
	return codeinfrax.Apply[*FuncWithListParamResult](o, func(v *FuncWithListParamResult) string { return v.R })
}
