// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Codeinfra.Serialization;

namespace Codeinfra.Example
{
    public static class ArgFunction
    {
        public static Task<ArgFunctionResult> InvokeAsync(ArgFunctionArgs? args = null, InvokeOptions? options = null)
            => global::Codeinfra.Deployment.Instance.InvokeAsync<ArgFunctionResult>("example::argFunction", args ?? new ArgFunctionArgs(), options.WithDefaults());

        public static Output<ArgFunctionResult> Invoke(ArgFunctionInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Codeinfra.Deployment.Instance.Invoke<ArgFunctionResult>("example::argFunction", args ?? new ArgFunctionInvokeArgs(), options.WithDefaults());

        public static Output<ArgFunctionResult> Invoke(ArgFunctionInvokeArgs args, InvokeOutputOptions options)
            => global::Codeinfra.Deployment.Instance.Invoke<ArgFunctionResult>("example::argFunction", args ?? new ArgFunctionInvokeArgs(), options.WithDefaults());
    }


    public sealed class ArgFunctionArgs : global::Codeinfra.InvokeArgs
    {
        [Input("name")]
        public Codeinfra.Random.RandomPet? Name { get; set; }

        public ArgFunctionArgs()
        {
        }
        public static new ArgFunctionArgs Empty => new ArgFunctionArgs();
    }

    public sealed class ArgFunctionInvokeArgs : global::Codeinfra.InvokeArgs
    {
        [Input("name")]
        public Input<Codeinfra.Random.RandomPet>? Name { get; set; }

        public ArgFunctionInvokeArgs()
        {
        }
        public static new ArgFunctionInvokeArgs Empty => new ArgFunctionInvokeArgs();
    }


    [OutputType]
    public sealed class ArgFunctionResult
    {
        public readonly int? Age;

        [OutputConstructor]
        private ArgFunctionResult(int? age)
        {
            Age = age;
        }
    }
}
