# coding=utf-8
# *** WARNING: this file was generated by codeinfra-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import codeinfra
import codeinfra.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'DataArgs',
]

@codeinfra.input_type
class DataArgs:
    def __init__(__self__, *,
                 bool_array: codeinfra.Input[Sequence[codeinfra.Input[bool]]],
                 boolean: codeinfra.Input[bool],
                 float: codeinfra.Input[float],
                 integer: codeinfra.Input[int],
                 string: codeinfra.Input[str],
                 string_map: codeinfra.Input[Mapping[str, codeinfra.Input[str]]]):
        codeinfra.set(__self__, "bool_array", bool_array)
        codeinfra.set(__self__, "boolean", boolean)
        codeinfra.set(__self__, "float", float)
        codeinfra.set(__self__, "integer", integer)
        codeinfra.set(__self__, "string", string)
        codeinfra.set(__self__, "string_map", string_map)

    @property
    @codeinfra.getter(name="boolArray")
    def bool_array(self) -> codeinfra.Input[Sequence[codeinfra.Input[bool]]]:
        return codeinfra.get(self, "bool_array")

    @bool_array.setter
    def bool_array(self, value: codeinfra.Input[Sequence[codeinfra.Input[bool]]]):
        codeinfra.set(self, "bool_array", value)

    @property
    @codeinfra.getter
    def boolean(self) -> codeinfra.Input[bool]:
        return codeinfra.get(self, "boolean")

    @boolean.setter
    def boolean(self, value: codeinfra.Input[bool]):
        codeinfra.set(self, "boolean", value)

    @property
    @codeinfra.getter
    def float(self) -> codeinfra.Input[float]:
        return codeinfra.get(self, "float")

    @float.setter
    def float(self, value: codeinfra.Input[float]):
        codeinfra.set(self, "float", value)

    @property
    @codeinfra.getter
    def integer(self) -> codeinfra.Input[int]:
        return codeinfra.get(self, "integer")

    @integer.setter
    def integer(self, value: codeinfra.Input[int]):
        codeinfra.set(self, "integer", value)

    @property
    @codeinfra.getter
    def string(self) -> codeinfra.Input[str]:
        return codeinfra.get(self, "string")

    @string.setter
    def string(self, value: codeinfra.Input[str]):
        codeinfra.set(self, "string", value)

    @property
    @codeinfra.getter(name="stringMap")
    def string_map(self) -> codeinfra.Input[Mapping[str, codeinfra.Input[str]]]:
        return codeinfra.get(self, "string_map")

    @string_map.setter
    def string_map(self, value: codeinfra.Input[Mapping[str, codeinfra.Input[str]]]):
        codeinfra.set(self, "string_map", value)


