// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ResourceWithAssets extends codeinfra.CustomResource {
    /**
     * Get an existing ResourceWithAssets resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: codeinfra.Input<codeinfra.ID>, opts?: codeinfra.CustomResourceOptions): ResourceWithAssets {
        return new ResourceWithAssets(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __codeinfraType = 'example:index:ResourceWithAssets';

    /**
     * Returns true if the given object is an instance of ResourceWithAssets.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourceWithAssets {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === ResourceWithAssets.__codeinfraType;
    }

    public readonly archive!: codeinfra.Output<codeinfra.asset.Archive>;
    public /*out*/ readonly asset!: codeinfra.Output<codeinfra.asset.Asset | codeinfra.asset.Archive>;
    public readonly nested!: codeinfra.Output<outputs.TypeWithAssets | undefined>;

    /**
     * Create a ResourceWithAssets resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceWithAssetsArgs, opts?: codeinfra.CustomResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["archive"] = args ? args.archive : undefined;
            resourceInputs["nested"] = args ? args.nested : undefined;
            resourceInputs["source"] = args ? args.source : undefined;
            resourceInputs["asset"] = undefined /*out*/;
        } else {
            resourceInputs["archive"] = undefined /*out*/;
            resourceInputs["asset"] = undefined /*out*/;
            resourceInputs["nested"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ResourceWithAssets.__codeinfraType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ResourceWithAssets resource.
 */
export interface ResourceWithAssetsArgs {
    archive?: codeinfra.Input<codeinfra.asset.Archive>;
    nested?: codeinfra.Input<inputs.TypeWithAssetsArgs>;
    source: codeinfra.Input<codeinfra.asset.Asset | codeinfra.asset.Archive>;
}
