// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Codeinfra.Serialization;

namespace Codeinfra.Example.Inputs
{

    public sealed class TypeWithAssetsArgs : global::Codeinfra.ResourceArgs
    {
        [Input("archive")]
        public Input<Archive>? Archive { get; set; }

        [Input("asset", required: true)]
        public Input<AssetOrArchive> Asset { get; set; } = null!;

        [Input("plainArchive", required: true)]
        public Archive PlainArchive { get; set; } = null!;

        [Input("plainAsset")]
        public AssetOrArchive? PlainAsset { get; set; }

        public TypeWithAssetsArgs()
        {
        }
        public static new TypeWithAssetsArgs Empty => new TypeWithAssetsArgs();
    }
}
