// *** WARNING: this file was generated by codeinfra-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Resource extends codeinfra.CustomResource {
    /**
     * Get an existing Resource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: codeinfra.Input<codeinfra.ID>, opts?: codeinfra.CustomResourceOptions): Resource {
        return new Resource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __codeinfraType = 'secret:index:Resource';

    /**
     * Returns true if the given object is an instance of Resource.  This is designed to work even
     * when multiple copies of the Codeinfra SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Resource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__codeinfraType'] === Resource.__codeinfraType;
    }

    public readonly private!: codeinfra.Output<string>;
    public readonly privateData!: codeinfra.Output<outputs.Data>;
    public readonly public!: codeinfra.Output<string>;
    public readonly publicData!: codeinfra.Output<outputs.Data>;

    /**
     * Create a Resource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceArgs, opts?: codeinfra.CustomResourceOptions) {
        let resourceInputs: codeinfra.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.private === undefined) && !opts.urn) {
                throw new Error("Missing required property 'private'");
            }
            if ((!args || args.privateData === undefined) && !opts.urn) {
                throw new Error("Missing required property 'privateData'");
            }
            if ((!args || args.public === undefined) && !opts.urn) {
                throw new Error("Missing required property 'public'");
            }
            if ((!args || args.publicData === undefined) && !opts.urn) {
                throw new Error("Missing required property 'publicData'");
            }
            resourceInputs["private"] = args?.private ? codeinfra.secret(args.private) : undefined;
            resourceInputs["privateData"] = args?.privateData ? codeinfra.secret(args.privateData) : undefined;
            resourceInputs["public"] = args ? args.public : undefined;
            resourceInputs["publicData"] = args ? args.publicData : undefined;
        } else {
            resourceInputs["private"] = undefined /*out*/;
            resourceInputs["privateData"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
            resourceInputs["publicData"] = undefined /*out*/;
        }
        opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["private", "privateData"] };
        opts = codeinfra.mergeOptions(opts, secretOpts);
        super(Resource.__codeinfraType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Resource resource.
 */
export interface ResourceArgs {
    private: codeinfra.Input<string>;
    privateData: codeinfra.Input<inputs.DataArgs>;
    public: codeinfra.Input<string>;
    publicData: codeinfra.Input<inputs.DataArgs>;
}
