// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
	"simple-plain-schema/example/internal"
)

func DoFoo(ctx *codeinfra.Context, args *DoFooArgs, opts ...codeinfra.InvokeOption) error {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv struct{}
	err := ctx.Invoke("example::doFoo", args, &rv, opts...)
	return err
}

type DoFooArgs struct {
	Foo Foo `codeinfra:"foo"`
}
