// Code generated by codeinfra-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package goodbye

import (
	"context"
	"reflect"

	"example.com/codeinfra-goodbye/sdk/go/v2/goodbye/internal"
	"github.com/khulnasoft/codeinfra/sdk/v3/go/codeinfra"
)

type Goodbye struct {
	codeinfra.CustomResourceState

	ParameterValue codeinfra.StringOutput `codeinfra:"parameterValue"`
}

// NewGoodbye registers a new resource with the given unique name, arguments, and options.
func NewGoodbye(ctx *codeinfra.Context,
	name string, args *GoodbyeArgs, opts ...codeinfra.ResourceOption) (*Goodbye, error) {
	if args == nil {
		args = &GoodbyeArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Goodbye
	err = ctx.RegisterPackageResource("goodbye:index:Goodbye", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGoodbye gets an existing Goodbye resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGoodbye(ctx *codeinfra.Context,
	name string, id codeinfra.IDInput, state *GoodbyeState, opts ...codeinfra.ResourceOption) (*Goodbye, error) {
	var resource Goodbye
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("goodbye:index:Goodbye", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Goodbye resources.
type goodbyeState struct {
}

type GoodbyeState struct {
}

func (GoodbyeState) ElementType() reflect.Type {
	return reflect.TypeOf((*goodbyeState)(nil)).Elem()
}

type goodbyeArgs struct {
}

// The set of arguments for constructing a Goodbye resource.
type GoodbyeArgs struct {
}

func (GoodbyeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*goodbyeArgs)(nil)).Elem()
}

type GoodbyeInput interface {
	codeinfra.Input

	ToGoodbyeOutput() GoodbyeOutput
	ToGoodbyeOutputWithContext(ctx context.Context) GoodbyeOutput
}

func (*Goodbye) ElementType() reflect.Type {
	return reflect.TypeOf((**Goodbye)(nil)).Elem()
}

func (i *Goodbye) ToGoodbyeOutput() GoodbyeOutput {
	return i.ToGoodbyeOutputWithContext(context.Background())
}

func (i *Goodbye) ToGoodbyeOutputWithContext(ctx context.Context) GoodbyeOutput {
	return codeinfra.ToOutputWithContext(ctx, i).(GoodbyeOutput)
}

type GoodbyeOutput struct{ *codeinfra.OutputState }

func (GoodbyeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Goodbye)(nil)).Elem()
}

func (o GoodbyeOutput) ToGoodbyeOutput() GoodbyeOutput {
	return o
}

func (o GoodbyeOutput) ToGoodbyeOutputWithContext(ctx context.Context) GoodbyeOutput {
	return o
}

func (o GoodbyeOutput) ParameterValue() codeinfra.StringOutput {
	return o.ApplyT(func(v *Goodbye) codeinfra.StringOutput { return v.ParameterValue }).(codeinfra.StringOutput)
}

func init() {
	codeinfra.RegisterInputType(reflect.TypeOf((*GoodbyeInput)(nil)).Elem(), &Goodbye{})
	codeinfra.RegisterOutputType(GoodbyeOutput{})
}
