// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as utilities from "./utilities";

export function getArchive(a?: number, opts?: codeinfra.InvokeOptions): Promise<codeinfra.asset.Archive> {
    opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return codeinfra.runtime.invokeSingle("std:index:GetArchive", {
        "a": a,
    }, opts);
}
export function getArchiveOutput(a?: codeinfra.Input<number | undefined>, opts?: codeinfra.InvokeOutputOptions): codeinfra.Output<codeinfra.asset.Archive> {
    opts = codeinfra.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return codeinfra.runtime.invokeSingleOutput("std:index:GetArchive", {
        "a": a,
    }, opts);
}
