// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as codeinfra from "@codeinfra/codeinfra";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace nested {
    export interface Baz {
        hello?: string;
        world?: string;
    }

    export interface BazArgs {
        hello?: codeinfra.Input<string>;
        world?: codeinfra.Input<string>;
    }
}
